In [2]:
from src.components.data_processing.data_loader import DataLoader, DataUtils
from loguru import logger
import polars.selectors as cs
import polars as pl

In [3]:
import os
import s3fs

os.environ["AWS_ACCESS_KEY_ID"] = "KGBESCEJ2L4ANCRPM0UB"
os.environ["AWS_SECRET_ACCESS_KEY"] = "GYb0HPOP1vKciDq8qOunyNTjGz+HD67XF3+4dd+6"
os.environ["AWS_SESSION_TOKEN"] = (
    "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJLR0JFU0NFSjJMNEFOQ1JQTTBVQiIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sImF1ZCI6WyJtaW5pby1kYXRhbm9kZSIsIm9ueXhpYSIsImFjY291bnQiXSwiYXV0aF90aW1lIjoxNzc4NDg0MjcxLCJhenAiOiJvbnl4aWEiLCJjbmYiOnsiamt0IjoiSE51MEVHcHVuQ3k1emRjcmhaWExGUWF0TjRPSVNFbWZtZnk1a3k3MlBINCJ9LCJlbWFpbCI6ImFydGh1ci5tYW5jZWF1QHN0dWRlbnQtY3MuZnIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzc5MDg5Mjc1LCJmYW1pbHlfbmFtZSI6Ik1hbmNlYXUiLCJnaXZlbl9uYW1lIjoiQXJ0aHVyIiwiZ3JvdXBzIjpbIlVTRVJfT05ZWElBIl0sImlhdCI6MTc3ODQ4NDQ3NSwiaXNzIjoiaHR0cHM6Ly9hdXRoLmxhYi5zc3BjbG91ZC5mci9hdXRoL3JlYWxtcy9zc3BjbG91ZCIsImp0aSI6Im9ucnRydDo0MTNkMDc4OS1mNjgxLTBjY2QtZTg5My1mYmY1YjU0OTkxZWQiLCJsb2NhbGUiOiJlbiIsIm5hbWUiOiJBcnRodXIgTWFuY2VhdSIsInBvbGljeSI6InN0c29ubHkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhcnRodXJtYW5jZWF1IiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXNzcGNsb3VkIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtc3NwY2xvdWQiXSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBncm91cHMgZW1haWwiLCJzaWQiOiJOQUk2UGw1VUwyd2VMazZCeHN4NElwTWsiLCJzdWIiOiJiYzc3Yjk3YS1lN2VkLTQ4ZWMtYmQ4Zi1lNzBjYjZhMTYyZGIiLCJ0eXAiOiJEUG9QIn0.ufLP0JGLNw9HdBPX1qbnZH9Q2gayd3iCfBR8n5VtamXHksBXtIsTSYc36C9UKn3Ugx1858v6BaxhprpwLWmmvw"
)
os.environ["AWS_DEFAULT_REGION"] = "us-east-1"
fs = s3fs.S3FileSystem(
    client_kwargs={"endpoint_url": "https://" + "minio.lab.sspcloud.fr"},
    key=os.environ["AWS_ACCESS_KEY_ID"],
    secret=os.environ["AWS_SECRET_ACCESS_KEY"],
    token=os.environ["AWS_SESSION_TOKEN"],
)

FIND a communes file with all the communes that existed and its history

In [3]:
communes = pl.scan_csv(
    "s3://arthurmanceau/election_modeling_uhcp/data/raw/insee_geo/2026/communes_2026.csv",
    storage_options=storage_options,
    infer_schema_length=40000,
).collect()

In [4]:
communes = communes.with_columns(
    DEP_NUM=pl.col("DEP").replace({"2A": 20, "2B": 20}).cast(pl.Int64),
    codecommune=pl.col("COM").cast(pl.String).str.zfill(5),
    codecommune_parent=pl.col("COMPARENT").cast(pl.String).str.zfill(5),
)

In [5]:
communes

shape: (37_496, 15)
┌─────────┬───────┬─────┬─────┬───┬───────────┬─────────┬─────────────┬────────────────────┐
│ TYPECOM ┆ COM   ┆ REG ┆ DEP ┆ … ┆ COMPARENT ┆ DEP_NUM ┆ codecommune ┆ codecommune_parent │
│ ---     ┆ ---   ┆ --- ┆ --- ┆   ┆ ---       ┆ ---     ┆ ---         ┆ ---                │
│ str     ┆ str   ┆ i64 ┆ str ┆   ┆ i64       ┆ i64     ┆ str         ┆ str                │
╞═════════╪═══════╪═════╪═════╪═══╪═══════════╪═════════╪═════════════╪════════════════════╡
│ COM     ┆ 1001  ┆ 84  ┆ 1   ┆ … ┆ null      ┆ 1       ┆ 01001       ┆ null               │
│ COM     ┆ 1002  ┆ 84  ┆ 1   ┆ … ┆ null      ┆ 1       ┆ 01002       ┆ null               │
│ COM     ┆ 1004  ┆ 84  ┆ 1   ┆ … ┆ null      ┆ 1       ┆ 01004       ┆ null               │
│ COM     ┆ 1005  ┆ 84  ┆ 1   ┆ … ┆ null      ┆ 1       ┆ 01005       ┆ null               │
│ COM     ┆ 1006  ┆ 84  ┆ 1   ┆ … ┆ null      ┆ 1       ┆ 01006       ┆ null               │
│ …       ┆ …     ┆ …   ┆ …   ┆ … ┆ …         ┆ …       ┆ …           ┆ …                  │
│ COM     ┆ 97613 ┆ 6   ┆ 976 ┆ … ┆ null      ┆ 976     ┆ 97613       ┆ null               │
│ COM     ┆ 97614 ┆ 6   ┆ 976 ┆ … ┆ null      ┆ 976     ┆ 97614       ┆ null               │
│ COM     ┆ 97615 ┆ 6   ┆ 976 ┆ … ┆ null      ┆ 976     ┆ 97615       ┆ null               │
│ COM     ┆ 97616 ┆ 6   ┆ 976 ┆ … ┆ null      ┆ 976     ┆ 97616       ┆ null               │
│ COM     ┆ 97617 ┆ 6   ┆ 976 ┆ … ┆ null      ┆ 976     ┆ 97617       ┆ null               │
└─────────┴───────┴─────┴─────┴───┴───────────┴─────────┴─────────────┴────────────────────┘

In [6]:
data_path = "s3://arthurmanceau/election_modeling_uhcp/data/"
elections_to_exclude = []

In [ ]:
def interpret_election_path(relative_path):
    path_element = relative_path.split(os.sep)[
        -3:
    ]  # ['legislative', '1848', 'leg1848_csv']
    election_type = path_element[0]  # 'legislative'
    year = path_element[1]  # '1848'
    election_code = path_element[2].split("_")[0]  # leg1848
    return election_type, year, election_code


electoral_schema = {
    "dep": pl.String,
    "nomdep": pl.String,
    "codecommune": pl.String,
    "nomcommune": pl.String,
    "year": pl.Int64,
    "type": pl.String,
    "election_code": pl.String,
    "inscrits": pl.Float64,
    "votants": pl.Float64,
    "exprimes": pl.Float64,
    # "inscritsT2": pl.Float64,
    # "votantsT2": pl.Float64,
    # "exprimesT2": pl.Float64,
    "voteG": pl.Float64,
    "voteCG": pl.Float64,
    "voteC": pl.Float64,
    "voteCD": pl.Float64,
    "voteD": pl.Float64,
    "voteTG": pl.Float64,
    "voteTD": pl.Float64,
    "voteGCG": pl.Float64,
    "voteDCD": pl.Float64,
    "voixOUI": pl.Float64,
    "voixNON": pl.Float64,
}


def load_electoral_data():
    """Function that loads all electoral dataset. A schema is defined for all elections."""
    folder_path = os.path.join(data_path + "raw/", "elections/")
    combined = None
    xs = DataUtils._create_fs() if DataUtils._detect_s3(data_path) else os
    for root, dirs, files in xs.walk(folder_path):
        for dir in dirs:
            for root, _, files in xs.walk(os.path.join(folder_path, dir)):
                for file in files:
                    if (
                        file.endswith(".parquet")
                        and (not file.startswith("."))
                        and file not in elections_to_exclude
                    ):
                        election_type, year, election_code = interpret_election_path(
                            os.path.relpath(root, folder_path)
                        )
                        logger.debug(f"Processing election : {(election_type, year)}")

                        file_path = DataUtils.path_helper(
                            folder_path, os.path.join(root, file)
                        )
                        df = pl.scan_parquet(file_path).collect()

                        df = df.with_columns(
                            year=pl.lit(year).cast(pl.Int64),
                            election_code=pl.lit(election_code),
                            type=pl.lit(election_type),
                            codecommune=pl.col("codecommune")
                            .cast(pl.String)
                            .str.zfill(5),
                        )
                        df = df.cast(
                            {
                                key: value
                                for key, value in electoral_schema.items()
                                if key in df.columns
                            }
                        )
                        df = df.match_to_schema(
                            electoral_schema,
                            missing_columns="insert",
                            extra_columns="ignore",
                        )
                        combined = df if combined is None else combined.vstack(df)

    return combined.rechunk()


socio_economic_schema = {
    "codecommune": pl.String,  # key
    "raw": pl.Float64,
    "variable": pl.String,
    "year": pl.Int64,  # key
    "feature_name": pl.String,  # key
    "lag": pl.Float64,
    "rank": pl.Float64,
    "delta": pl.Float64,
    "pct_change": pl.Float64,
}


def load_socio_economic_data():
    folder_path = os.path.join(data_path, "raw/")
    combined = None
    xs = DataUtils._create_fs() if DataUtils._detect_s3(data_path) else os
    for root, dirs, files in xs.walk(folder_path):
        for dir in dirs:
            if dir != "elections":
                for root, _, files in xs.walk(os.path.join(folder_path, dir)):
                    for file in files:
                        if file.endswith(".parquet") and (not file.startswith(".")):
                            # Only consider the relevant file : commune level
                            # How to integrate departemental data?
                            key = "codecommune"
                            if "communes" not in file:
                                continue

                            if file[:5] == "codes":
                                continue

                            file_path = DataUtils.path_helper(
                                folder_path, os.path.join(root, file)
                            )
                            data_code = file_path.split("/")[-1].split(".")[0]
                            logger.debug(f"Processing file : {data_code}")

                            df = pl.scan_parquet(file_path).collect()

                            # Identify features (time evolution)
                            all_feature_years = df.select(
                                cs.matches(r".*\d{4}$")
                            ).columns

                            # Single unpivot for all features
                            df_long = (
                                df.unpivot(
                                    on=all_feature_years,
                                    index=key,
                                    variable_name="variable",
                                    value_name="raw",
                                )
                                .with_columns(
                                    pl.col("raw").cast(pl.Float64, strict=False),
                                    year=pl.col("variable").str.tail(4).cast(pl.Int32),
                                    feature_name=pl.col("variable").str.head(-4),
                                )
                                .sort([key, "feature_name", "year"])
                                .with_columns(
                                    lag=pl.col("raw")
                                    .shift(1)
                                    .over(key, "feature_name"),
                                    rank=pl.col("raw")
                                    .rank("dense")
                                    .over(key, "feature_name"),
                                    delta=pl.col("raw")
                                    .diff(1)
                                    .over(key, "feature_name"),
                                    pct_change=pl.col("raw")
                                    .pct_change(1)
                                    .over(key, "feature_name"),
                                )
                                .fill_nan(None)
                            )
                            float_cols = [
                                c
                                for c, dtype in zip(df_long.columns, df_long.dtypes)
                                if dtype in (pl.Float32, pl.Float64)
                            ]
                            df_long = df_long.with_columns(
                                [
                                    pl.when(pl.col(c).is_infinite())
                                    .then(None)
                                    .otherwise(pl.col(c))
                                    .alias(c)
                                    for c in float_cols
                                ]
                            )
                            df_long = df_long.cast(
                                {
                                    key: value
                                    for key, value in socio_economic_schema.items()
                                    if key in df_long.columns
                                }
                            )
                            df_long = df_long.match_to_schema(
                                socio_economic_schema,
                                missing_columns="insert",
                                extra_columns="ignore",
                            )
                            combined = (
                                df_long
                                if combined is None
                                else combined.vstack(df_long)
                            )

    return combined.rechunk().fill_nan(None)

In [356]:
election_datasets = load_electoral_data()

2026-04-30 10:31:31.793 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1848')
2026-04-30 10:31:32.026 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1849')
2026-04-30 10:31:32.249 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1850')
2026-04-30 10:31:32.462 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1851')
2026-04-30 10:31:32.750 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1871')
2026-04-30 10:31:32.979 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1872')
2026-04-30 10:31:33.200 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1874')
2026-04-30 10:31:33.410 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1876')
2026-04-30 10:31:33.638 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1877')
2026-04-30 10:31:33.872 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1881')
2026-04-30 10:31:34.125 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1882')
2026-04-30 10:31:34.416 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1885')
2026-04-30 10:31:34.753 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1886')
2026-04-30 10:31:35.110 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1889')
2026-04-30 10:31:35.365 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1890')
2026-04-30 10:31:35.691 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1893')
2026-04-30 10:31:35.962 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1894')
2026-04-30 10:31:36.268 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1898')
2026-04-30 10:31:36.510 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1899')
2026-04-30 10:31:36.818 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1906')
2026-04-30 10:31:37.106 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1907')
2026-04-30 10:31:37.380 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1910')
2026-04-30 10:31:37.657 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1911')
2026-04-30 10:31:37.961 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1914')
2026-04-30 10:31:38.179 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1915')
2026-04-30 10:31:38.385 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1919')
2026-04-30 10:31:38.631 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1924')
2026-04-30 10:31:38.889 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1928')
2026-04-30 10:31:39.116 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1932')
2026-04-30 10:31:39.355 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1936')
2026-04-30 10:31:39.549 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1945')
2026-04-30 10:31:39.821 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1946')
2026-04-30 10:31:40.407 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1947')
2026-04-30 10:31:40.632 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1951')
2026-04-30 10:31:40.904 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1956')
2026-04-30 10:31:41.220 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1958')
2026-04-30 10:31:41.528 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1962')
2026-04-30 10:31:41.802 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1967')
2026-04-30 10:31:42.089 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1968')
2026-04-30 10:31:42.414 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1973')
2026-04-30 10:31:42.718 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1978')
2026-04-30 10:31:42.933 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1981')
2026-04-30 10:31:43.155 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1986')
2026-04-30 10:31:43.394 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1988')
2026-04-30 10:31:43.620 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1993')
2026-04-30 10:31:43.853 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '1997')
2026-04-30 10:31:44.198 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '2002')
2026-04-30 10:31:44.539 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '2007')
2026-04-30 10:31:44.886 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '2012')
2026-04-30 10:31:45.145 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '2017')
2026-04-30 10:31:45.470 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '2022')
2026-04-30 10:31:45.793 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('legislative', '2024')
2026-04-30 10:31:46.071 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('municipales', '2014')
2026-04-30 10:31:46.436 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('municipales', '2014')
2026-04-30 10:31:46.643 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('municipales', '2020')
2026-04-30 10:31:46.879 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('municipales', '2020')
2026-04-30 10:31:47.029 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('municipales', '2026')
2026-04-30 10:31:47.260 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('municipales', '2026')
2026-04-30 10:31:47.431 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('presidentiel', '1848')
2026-04-30 10:31:47.627 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('presidentiel', '1965')
2026-04-30 10:31:47.933 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('presidentiel', '1969')
2026-04-30 10:31:48.222 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('presidentiel', '1974')
2026-04-30 10:31:48.519 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('presidentiel', '1981')
2026-04-30 10:31:48.791 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('presidentiel', '1988')
2026-04-30 10:31:49.053 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('presidentiel', '1995')
2026-04-30 10:31:49.298 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('presidentiel', '2002')
2026-04-30 10:31:49.657 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('presidentiel', '2007')
2026-04-30 10:31:49.969 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('presidentiel', '2012')
2026-04-30 10:31:50.290 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('presidentiel', '2017')
2026-04-30 10:31:50.610 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('presidentiel', '2022')
2026-04-30 10:31:50.889 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('presidentiel', '2027')
2026-04-30 10:31:51.128 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('referendum', '1793')
2026-04-30 10:31:51.309 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('referendum', '1795')
2026-04-30 10:31:51.508 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('referendum', '1946')
2026-04-30 10:31:51.676 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('referendum', '1992')
2026-04-30 10:31:51.928 | DEBUG    | __main__:load_electoral_data:53 - Processing election : ('referendum', '2005')

In [379]:
# Filter out unvalid codecommune — only France metropolitaine
election_datasets = election_datasets.filter(
    (
        pl.col("codecommune").str.slice(0, 2).is_between(pl.lit("01"), pl.lit("95"))
        | pl.col("codecommune").str.slice(0, 2).is_in(["2A", "2B"])
    )
)

In [380]:
election_datasets

shape: (2_510_361, 38)
┌─────┬────────────┬─────────────┬─────────────────────┬───┬──────────┬──────────┬──────────┬──────┐
│ dep ┆ nomdep     ┆ codecommune ┆ nomcommune          ┆ … ┆ pvoteDCD ┆ pvoixOUI ┆ pvoixNON ┆ pabs │
│ --- ┆ ---        ┆ ---         ┆ ---                 ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---  │
│ str ┆ str        ┆ str         ┆ str                 ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64  │
╞═════╪════════════╪═════════════╪═════════════════════╪═══╪══════════╪══════════╪══════════╪══════╡
│ 01  ┆ AIN        ┆ 01002       ┆ ABERGEMENT-DE-VAREY ┆ … ┆ 0.52     ┆ null     ┆ null     ┆ 0.0  │
│ 01  ┆ AIN        ┆ 01004       ┆ AMBERIEU-EN-BUGEY   ┆ … ┆ 0.52     ┆ null     ┆ null     ┆ 0.0  │
│ 01  ┆ AIN        ┆ 01005       ┆ AMBERIEUX-EN-DOMBES ┆ … ┆ 0.56     ┆ null     ┆ null     ┆ 0.1  │
│ 01  ┆ AIN        ┆ 01006       ┆ AMBLEON             ┆ … ┆ 0.49     ┆ null     ┆ null     ┆ 0.1  │
│ 01  ┆ AIN        ┆ 01007       ┆ AMBRONAY            ┆ … ┆ 0.52     ┆ null     ┆ null     ┆ 0.0  │
│ …   ┆ …          ┆ …           ┆ …                   ┆ … ┆ …        ┆ …        ┆ …        ┆ …    │
│ 95  ┆ VAL D'OISE ┆ 95676       ┆ Villers-en-Arthies  ┆ … ┆ null     ┆ 0.53     ┆ 0.47     ┆ 0.25 │
│ 95  ┆ VAL D'OISE ┆ 95678       ┆ Villiers-Adam       ┆ … ┆ null     ┆ 0.45     ┆ 0.55     ┆ 0.19 │
│ 95  ┆ VAL D'OISE ┆ 95680       ┆ Villiers-le-Bel     ┆ … ┆ null     ┆ 0.36     ┆ 0.64     ┆ 0.43 │
│ 95  ┆ VAL D'OISE ┆ 95682       ┆ Villiers-le-Sec     ┆ … ┆ null     ┆ 0.51     ┆ 0.49     ┆ 0.19 │
│ 95  ┆ VAL D'OISE ┆ 95690       ┆ Wy-dit-Joli-Village ┆ … ┆ null     ┆ 0.6      ┆ 0.4      ┆ 0.2  │
└─────┴────────────┴─────────────┴─────────────────────┴───┴──────────┴──────────┴──────────┴──────┘

In [381]:
# Remove election for which we have no information
cols_to_check = [
    "inscrits",
    "votants",
    "exprimes",
    "voteG",
    "voteCG",
    "voteC",
    "voteCD",
    "voteD",
    "voteTG",
    "voteTD",
    "voteGCG",
    "voteDCD",
    "voixOUI",
    "voixNON",
]

election_datasets = election_datasets.filter(
    ~pl.all_horizontal(pl.col(cols_to_check).is_null())
)
election_datasets.null_count()

shape: (1, 38)
┌─────┬────────┬─────────────┬────────────┬───┬──────────┬──────────┬──────────┬──────┐
│ dep ┆ nomdep ┆ codecommune ┆ nomcommune ┆ … ┆ pvoteDCD ┆ pvoixOUI ┆ pvoixNON ┆ pabs │
│ --- ┆ ---    ┆ ---         ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---  │
│ u32 ┆ u32    ┆ u32         ┆ u32        ┆   ┆ u32      ┆ u32      ┆ u32      ┆ u32  │
╞═════╪════════╪═════════════╪════════════╪═══╪══════════╪══════════╪══════════╪══════╡
│ 0   ┆ 0      ┆ 0           ┆ 0          ┆ … ┆ 174235   ┆ 2314408  ┆ 2314408  ┆ 0    │
└─────┴────────┴─────────────┴────────────┴───┴──────────┴──────────┴──────────┴──────┘

In [382]:
cols_to_zero_inscrits = [
    "votants",
    "exprimes",
    "voteG",
    "voteCG",
    "voteC",
    "voteCD",
    "voteD",
    "voteTG",
    "voteTD",
    "voteGCG",
    "voteDCD",
    "voixOUI",
    "voixNON",
]

cols_to_zero_votants = [
    "exprimes",
    "voteG",
    "voteCG",
    "voteC",
    "voteCD",
    "voteD",
    "voteTG",
    "voteTD",
    "voteGCG",
    "voteDCD",
    "voixOUI",
    "voixNON",
]

election_datasets = election_datasets.with_columns(
    # Zero out cols when inscrits == 0
    [
        pl.when(pl.col("inscrits") == 0).then(0).otherwise(pl.col(c)).alias(c)
        for c in cols_to_zero_inscrits
    ]
    + [
        pl.when(pl.col("inscrits") == 0)
        .then(pl.lit(True))
        .otherwise(pl.lit(False))
        .alias("no_inscrits")
    ]
).with_columns(
    # Zero out cols when votants == 0
    [
        pl.when(pl.col("votants") == 0).then(0).otherwise(pl.col(c)).alias(c)
        for c in cols_to_zero_votants
    ]
    + [
        pl.when(pl.col("votants") == 0)
        .then(pl.lit(True))
        .otherwise(pl.lit(False))
        .alias("no_votants")
    ]
)
print(election_datasets.filter(pl.col("inscrits") < 0).height)
print(election_datasets.filter(pl.col("votants") < 0).height)

0
0

In [383]:
# Data quality checks on election data

# 1. No negative amount in vote columns
vote_cols = [
    "inscrits",
    "votants",
    "exprimes",
    "inscritsT2",
    "votantsT2",
    "exprimesT2",
    "voteG",
    "voteCG",
    "voteC",
    "voteCD",
    "voteD",
    "voteTG",
    "voteTD",
    "voteGCG",
    "voteDCD",
    "voixOUI",
    "voixNON",
]

df_negative = election_datasets.filter(
    pl.any_horizontal(
        *[pl.col(c) < 0 for c in vote_cols if c in election_datasets.columns]
    )
)
df_negative
# One outlier rows for leg1871juil, removing it

shape: (1, 38)
┌─────┬────────────────┬─────────────┬───────────────┬───┬──────────┬──────────┬──────────┬──────┐
│ dep ┆ nomdep         ┆ codecommune ┆ nomcommune    ┆ … ┆ pvoteDCD ┆ pvoixOUI ┆ pvoixNON ┆ pabs │
│ --- ┆ ---            ┆ ---         ┆ ---           ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---  │
│ str ┆ str            ┆ str         ┆ str           ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64  │
╞═════╪════════════════╪═════════════╪═══════════════╪═══╪══════════╪══════════╪══════════╪══════╡
│ 76  ┆ SEINE-MARITIME ┆ 76362       ┆ HEURTEAUVILLE ┆ … ┆ 0.24     ┆ null     ┆ null     ┆ 0.56 │
└─────┴────────────────┴─────────────┴───────────────┴───┴──────────┴──────────┴──────────┴──────┘

In [385]:
election_datasets.filter(pl.col("inscrits") == 0)

shape: (21_589, 38)
┌─────┬─────────────────┬─────────────┬────────────────┬───┬──────────┬──────────┬──────────┬──────┐
│ dep ┆ nomdep          ┆ codecommune ┆ nomcommune     ┆ … ┆ pvoteDCD ┆ pvoixOUI ┆ pvoixNON ┆ pabs │
│ --- ┆ ---             ┆ ---         ┆ ---            ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---  │
│ str ┆ str             ┆ str         ┆ str            ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64  │
╞═════╪═════════════════╪═════════════╪════════════════╪═══╪══════════╪══════════╪══════════╪══════╡
│ 01  ┆ AIN             ┆ 01059       ┆ BRENAZ         ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0  │
│ 01  ┆ AIN             ┆ 01091       ┆ CHATILLON-EN-M ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0  │
│     ┆                 ┆             ┆ ICHAILLE       ┆   ┆          ┆          ┆          ┆      │
│ 01  ┆ AIN             ┆ 01097       ┆ CHAVORNAY      ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0  │
│ 01  ┆ AIN             ┆ 01119       ┆ CORCELLES      ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0  │
│ 01  ┆ AIN             ┆ 01122       ┆ CORMARANCHE-EN ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0  │
│     ┆                 ┆             ┆ -BUGEY         ┆   ┆          ┆          ┆          ┆      │
│ …   ┆ …               ┆ …           ┆ …              ┆ … ┆ …        ┆ …        ┆ …        ┆ …    │
│ 90  ┆ TERRITOIRE DE   ┆ 90040       ┆ ETUEFFONT-BAS  ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0  │
│     ┆ BELFORT         ┆             ┆                ┆   ┆          ┆          ┆          ┆      │
│ 90  ┆ TERRITOIRE DE   ┆ 90073       ┆ MOVAL          ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0  │
│     ┆ BELFORT         ┆             ┆                ┆   ┆          ┆          ┆          ┆      │
│ 90  ┆ TERRITOIRE DE   ┆ 90092       ┆ SALBERT        ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0  │
│     ┆ BELFORT         ┆             ┆                ┆   ┆          ┆          ┆          ┆      │
│ 90  ┆ TERRITOIRE DE   ┆ 90106       ┆ VOURVENANS     ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0  │
│     ┆ BELFORT         ┆             ┆                ┆   ┆          ┆          ┆          ┆      │
│ 91  ┆ ESSONNE         ┆ 91222       ┆ ESTOUCHES      ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0  │
└─────┴─────────────────┴─────────────┴────────────────┴───┴──────────┴──────────┴──────────┴──────┘

In [386]:
election_datasets.filter(pl.col("inscrits") > 0).filter(pl.col("votants") == 0)

shape: (212, 38)
┌─────┬───────────┬─────────────┬──────────────────────┬───┬──────────┬──────────┬──────────┬──────┐
│ dep ┆ nomdep    ┆ codecommune ┆ nomcommune           ┆ … ┆ pvoteDCD ┆ pvoixOUI ┆ pvoixNON ┆ pabs │
│ --- ┆ ---       ┆ ---         ┆ ---                  ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---  │
│ str ┆ str       ┆ str         ┆ str                  ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64  │
╞═════╪═══════════╪═════════════╪══════════════════════╪═══╪══════════╪══════════╪══════════╪══════╡
│ 21  ┆ COTE-D'OR ┆ 21161       ┆ CHAUMONT-LE-BOIS     ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 1.0  │
│ 21  ┆ COTE-D'OR ┆ 21198       ┆ CORROMBLES           ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 1.0  │
│ 21  ┆ COTE-D'OR ┆ 21272       ┆ FLEE                 ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 1.0  │
│ 21  ┆ COTE-D'OR ┆ 21368       ┆ MAGNY-LES-VILLERS    ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 1.0  │
│ 21  ┆ COTE-D'OR ┆ 21382       ┆ MARCILLY-OGNY        ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 1.0  │
│ …   ┆ …         ┆ …           ┆ …                    ┆ … ┆ …        ┆ …        ┆ …        ┆ …    │
│ 85  ┆ VENDEE    ┆ 85197       ┆ SAINT-ANDRE-TREIZE-V ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 1.0  │
│     ┆           ┆             ┆ OIES                 ┆   ┆          ┆          ┆          ┆      │
│ 85  ┆ VENDEE    ┆ 85215       ┆ SAINT-FULGENT        ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 1.0  │
│ 85  ┆ VENDEE    ┆ 85262       ┆ SAINT-PHILBERT-DE-BO ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 1.0  │
│     ┆           ┆             ┆ UAINE                ┆   ┆          ┆          ┆          ┆      │
│ 85  ┆ VENDEE    ┆ 85295       ┆ TREIZE-SEPTIERS      ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 1.0  │
│ 55  ┆ MEUSE     ┆ 55189       ┆ FLEURY DT DOUAUMONT  ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 1.0  │
└─────┴───────────┴─────────────┴──────────────────────┴───┴──────────┴──────────┴──────────┴──────┘

In [387]:
# Be careful :
# - Inscrits and votants are two columns that go in pairs and we have inscrits > votants
# - Exprimes and vote columns go together and their sum should be equal
# But we don't have a match between votants and exprimes !

In [388]:
# On outlier row
election_datasets.filter(pl.col("inscrits").round(0) < pl.col("votants").round(0))

shape: (1, 38)
┌─────┬────────┬─────────────┬──────────────────────┬───┬──────────┬──────────┬──────────┬──────┐
│ dep ┆ nomdep ┆ codecommune ┆ nomcommune           ┆ … ┆ pvoteDCD ┆ pvoixOUI ┆ pvoixNON ┆ pabs │
│ --- ┆ ---    ┆ ---         ┆ ---                  ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---  │
│ str ┆ str    ┆ str         ┆ str                  ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64  │
╞═════╪════════╪═════════════╪══════════════════════╪═══╪══════════╪══════════╪══════════╪══════╡
│ 60  ┆ Oise   ┆ 60400       ┆ Le Mesnil-sur-Bulles ┆ … ┆ 0.0      ┆ null     ┆ null     ┆ 0.0  │
└─────┴────────┴─────────────┴──────────────────────┴───┴──────────┴──────────┴──────────┴──────┘

In [389]:
# Check the coherence of the number of voix
# Ok very few desc only in 2022. We exclude municipales and referundum
election_datasets_check = (
    election_datasets.filter(~(pl.col("type").is_in(["municipales", "referendum"])))
    .with_columns(
        (
            pl.sum_horizontal(
                "voteG", "voteCG", "voteC", "voteCD", "voteD", "voixOUI", "voixNON"
            )
        ).alias("total_voix_5_blocs"),
        (
            pl.sum_horizontal(
                "voteG", "voteCG", "voteC", "voteCD", "voteD", "voixOUI", "voixNON"
            ).round(0)
            == pl.col("exprimes").round(0)
        ).alias("matching_voix_5_blocs"),
        (
            pl.sum_horizontal(
                "voteGCG", "voteC", "voteDCD", "voixOUI", "voixNON"
            ).round(0)
            == pl.col("exprimes").round(0)
        ).alias("matching_voix_3_blocs"),
        (
            pl.sum_horizontal("voteTG", "voteTD", "voixOUI", "voixNON").round(0)
            == pl.col("exprimes").round(0)
        ).alias("matching_voix_2_blocs"),
    )
    .with_columns(
        (pl.col("exprimes") - pl.col("total_voix_5_blocs")).alias("diff"),
        (pl.col("inscrits") - pl.col("total_voix_5_blocs")).alias("diff_inscrits"),
    )
)
print(election_datasets_check.height)
print(election_datasets_check.filter(pl.col("matching_voix_5_blocs") == False))
# Correction to have exprimes == sum_voix
election_datasets = election_datasets.with_columns(
    exprimes_=pl.sum_horizontal(
        "voteG", "voteCG", "voteC", "voteCD", "voteD", "voixOUI", "voixNON"
    )
)

2219210
shape: (4, 44)
┌─────┬──────────┬─────────────┬──────────────┬───┬─────────────┬─────────────┬──────┬─────────────┐
│ dep ┆ nomdep   ┆ codecommune ┆ nomcommune   ┆ … ┆ matching_vo ┆ matching_vo ┆ diff ┆ diff_inscri │
│ --- ┆ ---      ┆ ---         ┆ ---          ┆   ┆ ix_3_blocs  ┆ ix_2_blocs  ┆ ---  ┆ ts          │
│ str ┆ str      ┆ str         ┆ str          ┆   ┆ ---         ┆ ---         ┆ f64  ┆ ---         │
│     ┆          ┆             ┆              ┆   ┆ bool        ┆ bool        ┆      ┆ f64         │
╞═════╪══════════╪═════════════╪══════════════╪═══╪═════════════╪═════════════╪══════╪═════════════╡
│ 16  ┆ Charente ┆ 16029       ┆ Bardenac     ┆ … ┆ false       ┆ false       ┆ 2.0  ┆ 66.0        │
│ 27  ┆ Eure     ┆ 27322       ┆ La Haye-Malh ┆ … ┆ false       ┆ false       ┆ -1.0 ┆ 317.0       │
│     ┆          ┆             ┆ erbe         ┆   ┆             ┆             ┆      ┆             │
│ 34  ┆ Hérault  ┆ 34316       ┆ Usclas-du-Bo ┆ … ┆ false       ┆ false       ┆ -1.0 ┆ 34.0        │
│     ┆          ┆             ┆ sc           ┆   ┆             ┆             ┆      ┆             │
│ 75  ┆ Paris    ┆ 75056       ┆ Paris        ┆ … ┆ false       ┆ false       ┆ 2.0  ┆ 377669.0    │
└─────┴──────────┴─────────────┴──────────────┴───┴─────────────┴─────────────┴──────┴─────────────┘

In [390]:
p_cols = [
    "ppar",
    "pvoteG",
    "pvoteCG",
    "pvoteC",
    "pvoteCD",
    "pvoteD",
    "pvoteTG",
    "pvoteTD",
    "pvoteGCG",
    "pvoteDCD",
    "pvoixOUI",
    "pvoixNON",
    "pabs",
]

election_datasets = (
    election_datasets.with_columns(
        ppar=pl.col("votants") / pl.col("inscrits"),
        abstentions=pl.col("inscrits") - pl.col("votants"),
        pvoteG=pl.col("voteG") / pl.col("exprimes_"),
        pvoteCG=pl.col("voteCG") / pl.col("exprimes_"),
        pvoteC=pl.col("voteC") / pl.col("exprimes_"),
        pvoteCD=pl.col("voteCD") / pl.col("exprimes_"),
        pvoteD=pl.col("voteD") / pl.col("exprimes_"),
        pvoteTG=pl.col("voteTG") / pl.col("exprimes_"),
        pvoteTD=pl.col("voteTD") / pl.col("exprimes_"),
        pvoteGCG=pl.col("voteGCG") / pl.col("exprimes_"),
        pvoteDCD=pl.col("voteDCD") / pl.col("exprimes_"),
        pvoixOUI=pl.col("voixOUI") / pl.col("exprimes_"),
        pvoixNON=pl.col("voixNON") / pl.col("exprimes_"),
    )
    .with_columns(
        pabs=pl.col("abstentions") / pl.col("inscrits"),
    )
    .with_columns(
        # Replace NaN (0/0) and inf (n/0) with 0
        pl.col(p_cols).fill_nan(0).clip(lower_bound=0, upper_bound=1.0)
    )
    .with_columns(pl.col(p_cols).round(2))
)

# Assert all p* columns are between 0 and 1
out_of_range = election_datasets.filter(
    pl.any_horizontal(*[(pl.col(c) < 0) | (pl.col(c) > 1) for c in p_cols])
)

out_of_range

shape: (0, 38)
┌─────┬────────┬─────────────┬────────────┬───┬──────────┬──────────┬──────────┬──────┐
│ dep ┆ nomdep ┆ codecommune ┆ nomcommune ┆ … ┆ pvoteDCD ┆ pvoixOUI ┆ pvoixNON ┆ pabs │
│ --- ┆ ---    ┆ ---         ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---  │
│ str ┆ str    ┆ str         ┆ str        ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64  │
╞═════╪════════╪═════════════╪════════════╪═══╪══════════╪══════════╪══════════╪══════╡
└─────┴────────┴─────────────┴────────────┴───┴──────────┴──────────┴──────────┴──────┘

In [232]:
socio_economic_data = load_socio_economic_data()

2026-04-30 08:44:23.342 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : agesexcommunes
2026-04-30 08:44:45.064 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : menagescommunes
2026-04-30 08:44:45.237 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : crimesdelitscommunes
2026-04-30 08:44:48.802 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : cspcommunes
2026-04-30 08:45:21.421 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : empfoncommunes
2026-04-30 08:45:27.740 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : emploicommunes
2026-04-30 08:45:28.849 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : rsacommunes
2026-04-30 08:45:30.031 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : basesfiscalescommunes
2026-04-30 08:45:47.187 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : capitalimmobiliercommunes
2026-04-30 08:45:58.903 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : isfcommunes
2026-04-30 08:45:59.079 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : terrescommunes
2026-04-30 08:46:00.261 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : diplomescommunes
2026-04-30 08:46:09.895 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : publicprivecommunes1894
2026-04-30 08:46:10.360 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : publicprivecommunes2021
2026-04-30 08:46:13.752 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : religiositecommunes
2026-04-30 08:46:14.952 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : religiositecommunes1791
2026-04-30 08:46:16.488 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : etrangerscommunes
2026-04-30 08:46:23.113 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : naticommunes
2026-04-30 08:46:31.482 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : proprietairescommunes
2026-04-30 08:46:35.104 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : pibcommunes
2026-04-30 08:46:41.265 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : revcommunes
2026-04-30 08:46:57.510 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : popcommunes
2026-04-30 08:47:04.300 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : popcommuneselecteurs
2026-04-30 08:47:05.863 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : popcommunesvbbm
2026-04-30 08:47:10.885 | DEBUG    | __main__:load_socio_economic_data:115 - Processing file : alphabetisationcommunes

In [235]:
# Check there is non inf or NaN : all replace by Null
nan_counts = socio_economic_data.drop("codecommune", "feature_name", "variable").select(
    pl.all().is_nan().sum()
)
print("NaN")
print(nan_counts)
print(nan_counts.sum_horizontal().item())

# Which columns have any inf?
inf_counts = socio_economic_data.drop("codecommune", "feature_name", "variable").select(
    pl.all().is_infinite().sum()
)
print("Inf")
print(inf_counts)
print(inf_counts.sum_horizontal().item())

NaN
shape: (1, 6)
┌─────┬──────┬─────┬──────┬───────┬────────────┐
│ raw ┆ year ┆ lag ┆ rank ┆ delta ┆ pct_change │
│ --- ┆ ---  ┆ --- ┆ ---  ┆ ---   ┆ ---        │
│ u32 ┆ u32  ┆ u32 ┆ u32  ┆ u32   ┆ u32        │
╞═════╪══════╪═════╪══════╪═══════╪════════════╡
│ 0   ┆ 0    ┆ 0   ┆ 0    ┆ 0     ┆ 0          │
└─────┴──────┴─────┴──────┴───────┴────────────┘
0
Inf
shape: (1, 6)
┌─────┬──────┬─────┬──────┬───────┬────────────┐
│ raw ┆ year ┆ lag ┆ rank ┆ delta ┆ pct_change │
│ --- ┆ ---  ┆ --- ┆ ---  ┆ ---   ┆ ---        │
│ u32 ┆ u32  ┆ u32 ┆ u32  ┆ u32   ┆ u32        │
╞═════╪══════╪═════╪══════╪═══════╪════════════╡
│ 0   ┆ 0    ┆ 0   ┆ 0    ┆ 0     ┆ 0          │
└─────┴──────┴─────┴──────┴───────┴────────────┘
0

In [236]:
result = socio_economic_data.group_by("feature_name").agg(
    pl.col("year").unique().sort()
)

In [237]:
result

shape: (267, 2)
┌──────────────────────────┬──────────────────────┐
│ feature_name             ┆ year                 │
│ ---                      ┆ ---                  │
│ str                      ┆ list[i64]            │
╞══════════════════════════╪══════════════════════╡
│ franatur                 ┆ [1962, 1975, 1990]   │
│ nprim                    ┆ [2021]               │
│ paica                    ┆ [1960, 1961, … 2022] │
│ adm                      ┆ [1982, 1990, … 2016] │
│ pconjsign                ┆ [1686, 1786, … 1905] │
│ …                        ┆ …                    │
│ peragri                  ┆ [1790, 1791, … 2022] │
│ recetteimpotslocauxratio ┆ [1881, 1911, … 2022] │
│ prixm2                   ┆ [2014, 2015, … 2022] │
│ percapi                  ┆ [1790, 1791, … 2022] │
│ agef                     ┆ [1960, 1961, … 2022] │
└──────────────────────────┴──────────────────────┘

In [238]:
from shapely.geometry import shape


def add_geographical_data():
    """Add geographical coordinates from GeoJSON file"""
    logger.info("Adding geographical data...")

    geo_data_path = data_path + "raw/geo_data/communes.geojson"

    fs = DataUtils._create_fs() if DataUtils._detect_s3(geo_data_path) else None
    if not DataUtils._exists(geo_data_path, fs):
        logger.warning(
            f"GeoJSON file not found at {geo_data_path}. Skipping geographical data."
        )
        return None

    # Load the GeoJSON map of French communes
    communes_geojson = DataLoader.load_geojson(geo_data_path)

    geo_data = []
    for feature in communes_geojson["features"]:
        commune_geom = shape(feature["geometry"])
        lat = float(commune_geom.centroid.x)
        long = float(commune_geom.centroid.y)
        codecommune = feature["properties"]["code"]
        geo_data.append({"codecommune": codecommune, "lat": lat, "long": long})

        # Handle PARIS / LYON / MARSEILLE
        if codecommune == "13055":
            for i in range(1, 16 + 1):
                if i < 10:
                    geo_data.append(
                        {"codecommune": f"1320{i}", "lat": lat, "long": long}
                    )
                else:
                    geo_data.append(
                        {"codecommune": f"132{i}", "lat": lat, "long": long}
                    )
        if codecommune == "69123":
            for i in range(1, 9 + 1):
                geo_data.append({"codecommune": f"6938{i}", "lat": lat, "long": long})
        if codecommune == "75056":
            for i in range(1, 20 + 1):
                if i < 10:
                    geo_data.append(
                        {"codecommune": f"7510{i}", "lat": lat, "long": long}
                    )
                else:
                    geo_data.append(
                        {"codecommune": f"751{i}", "lat": lat, "long": long}
                    )

    return pl.DataFrame(geo_data).sort("codecommune")

In [239]:
geo_data = add_geographical_data()

2026-04-30 08:48:23.970 | INFO     | __main__:add_geographical_data:5 - Adding geographical data...
2026-04-30 08:48:25.639 | DEBUG    | src.components.data_processing.data_loader:load_geojson:217 - Geojson loaded

In [240]:
geo_data = geo_data.with_columns(
    lat=pl.col("lat").round(4), long=pl.col("long").round(4)
)
geo_data

shape: (35_273, 3)
┌─────────────┬────────┬─────────┐
│ codecommune ┆ lat    ┆ long    │
│ ---         ┆ ---    ┆ ---     │
│ str         ┆ f64    ┆ f64     │
╞═════════════╪════════╪═════════╡
│ 01001       ┆ 4.9258 ┆ 46.1536 │
│ 01002       ┆ 5.428  ┆ 46.0096 │
│ 01004       ┆ 5.3724 ┆ 45.961  │
│ 01005       ┆ 4.9119 ┆ 45.9962 │
│ 01006       ┆ 5.5946 ┆ 45.7498 │
│ …           ┆ …      ┆ …       │
│ 95676       ┆ 1.7306 ┆ 49.0861 │
│ 95678       ┆ 2.2389 ┆ 49.0699 │
│ 95680       ┆ 2.4039 ┆ 49.0079 │
│ 95682       ┆ 2.3867 ┆ 49.0745 │
│ 95690       ┆ 1.8244 ┆ 49.0959 │
└─────────────┴────────┴─────────┘

In [241]:
communes = (
    communes.join(geo_data, on="codecommune", how="left")
    # Step 1: fill from parent commune
    .join(
        geo_data.select(["codecommune", "lat", "long"]).rename(
            {"lat": "lat_parent", "long": "long_parent"}
        ),
        left_on="codecommune_parent",
        right_on="codecommune",
        how="left",
    )
    .with_columns(
        lat=pl.col("lat").fill_null(pl.col("lat_parent")),
        long=pl.col("long").fill_null(pl.col("long_parent")),
    )
    .drop(["lat_parent", "long_parent"])
    # Step 2: replace NaN with null so fill_null works on them too
    .with_columns(
        pl.col("lat").fill_nan(None),
        pl.col("long").fill_nan(None),
    )
    # Step 3: fill remaining nulls with department mean
    .with_columns(
        lat=pl.col("lat").fill_null(pl.col("lat").mean().over("DEP")),
        long=pl.col("long").fill_null(pl.col("long").mean().over("DEP")),
    )
)

In [242]:
# Communes d'outre mer
communes.filter(pl.col("lat").is_null()).get_column("DEP").value_counts()

shape: (5, 2)
┌─────┬───────┐
│ DEP ┆ count │
│ --- ┆ ---   │
│ str ┆ u32   │
╞═════╪═══════╡
│ 971 ┆ 32    │
│ 976 ┆ 17    │
│ 972 ┆ 34    │
│ 974 ┆ 24    │
│ 973 ┆ 22    │
└─────┴───────┘

In [243]:
def data_quality_checks(df):
    # Which columns have any NaN?
    nan_counts = df.select(pl.all().is_nan().sum())
    print("NaN")
    print(nan_counts)
    print(nan_counts.sum_horizontal().item())

    # Which columns have any Null?
    null_counts = df.select(pl.all().is_null().sum())
    print("Null")
    print(null_counts)
    print(null_counts.sum_horizontal().item())

    # Which columns have any inf?
    inf_counts = df.select(pl.all().is_infinite().sum())
    print("Inf")
    print(inf_counts)
    print(inf_counts.sum_horizontal().item())

In [306]:
def get_features_for_years(
    X,
    year=2022,
    feature_aug=["raw", "lag", "rank", "delta", "pct_change"],
    n_years_back=0,
):
    index_cols = ["codecommune"]

    # Base: pivot for the election year
    data = (
        X.filter(pl.col("year") == year)
        .pivot(
            on="feature_name",
            index=["year", "codecommune"],
            values=feature_aug,
            aggregate_function="first",
        )
        .sort("codecommune")
    )

    # Iteratively join each year back
    for i in range(1, n_years_back + 1):
        year_back = year - i
        df_back = (
            X.filter(pl.col("year") == year_back)
            .pivot(
                on="feature_name",
                index=["year", "codecommune"],
                values=feature_aug,
                aggregate_function="first",
            )
            .sort("codecommune")
        )

        new_cols = [
            c for c in df_back.columns if c not in data.columns and c not in index_cols
        ]

        data = data.join(
            df_back.select(index_cols + new_cols).rename(
                {c: f"{c}|minus_{i}" for c in new_cols}
            ),
            on=index_cols,
            how="left",
        )

    return data

In [315]:
X = get_features_for_years(
    socio_economic_data,
    year=2022,
    feature_aug=["raw", "lag", "rank", "delta", "pct_change"],
    n_years_back=0,
)

In [316]:
X

shape: (41_500, 657)
┌──────┬────────────┬───────────┬───────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ year ┆ codecommun ┆ raw_age   ┆ raw_agef  ┆ … ┆ pct_change ┆ pct_change ┆ pct_change ┆ pct_chang │
│ ---  ┆ e          ┆ ---       ┆ ---       ┆   ┆ _electeurs ┆ _vbbm      ┆ _vbbmpauvr ┆ e_vbbmpau │
│ i64  ┆ ---        ┆ f64       ┆ f64       ┆   ┆ ---        ┆ ---        ┆ esriches   ┆ vresriche │
│      ┆ str        ┆           ┆           ┆   ┆ f64        ┆ f64        ┆ ---        ┆ sca…      │
│      ┆            ┆           ┆           ┆   ┆            ┆            ┆ f64        ┆ ---       │
│      ┆            ┆           ┆           ┆   ┆            ┆            ┆            ┆ f64       │
╞══════╪════════════╪═══════════╪═══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 2022 ┆ .          ┆ null      ┆ null      ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 2022 ┆ ..         ┆ null      ┆ null      ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 2022 ┆ ...        ┆ null      ┆ null      ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 2022 ┆ 01001      ┆ 44.203548 ┆ 43.147369 ┆ … ┆ 0.002467   ┆ 0.0        ┆ 0.0        ┆ 0.0       │
│ 2022 ┆ 01002      ┆ 36.973824 ┆ 27.685621 ┆ … ┆ -0.006909  ┆ 0.0        ┆ 0.0        ┆ 0.0       │
│ …    ┆ …          ┆ …         ┆ …         ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ 2022 ┆ 95Z001     ┆ null      ┆ null      ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 2022 ┆ 95Z002     ┆ null      ┆ null      ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 2022 ┆ 95Z003     ┆ null      ┆ null      ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 2022 ┆ ECOCHE     ┆ null      ┆ null      ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 2022 ┆ nan        ┆ null      ┆ null      ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
└──────┴────────────┴───────────┴───────────┴───┴────────────┴────────────┴────────────┴───────────┘

Creation of a dataset for a given election : election_code

## Pipeline

In [543]:
election_code = "pres2017"

In [544]:
# Step 1: get all communes
communes

shape: (37_496, 19)
┌─────────┬───────┬─────┬─────┬───┬──────────┬───────────┬───────────┬────────────┐
│ TYPECOM ┆ COM   ┆ REG ┆ DEP ┆ … ┆ lat      ┆ long      ┆ lat_right ┆ long_right │
│ ---     ┆ ---   ┆ --- ┆ --- ┆   ┆ ---      ┆ ---       ┆ ---       ┆ ---        │
│ str     ┆ str   ┆ i64 ┆ str ┆   ┆ f64      ┆ f64       ┆ f64       ┆ f64        │
╞═════════╪═══════╪═════╪═════╪═══╪══════════╪═══════════╪═══════════╪════════════╡
│ COM     ┆ 1001  ┆ 84  ┆ 1   ┆ … ┆ 4.925824 ┆ 46.153595 ┆ 4.9258    ┆ 46.1536    │
│ COM     ┆ 1002  ┆ 84  ┆ 1   ┆ … ┆ 5.427993 ┆ 46.009579 ┆ 5.428     ┆ 46.0096    │
│ COM     ┆ 1004  ┆ 84  ┆ 1   ┆ … ┆ 5.372353 ┆ 45.961045 ┆ 5.3724    ┆ 45.961     │
│ COM     ┆ 1005  ┆ 84  ┆ 1   ┆ … ┆ 4.911941 ┆ 45.996194 ┆ 4.9119    ┆ 45.9962    │
│ COM     ┆ 1006  ┆ 84  ┆ 1   ┆ … ┆ 5.594622 ┆ 45.749777 ┆ 5.5946    ┆ 45.7498    │
│ …       ┆ …     ┆ …   ┆ …   ┆ … ┆ …        ┆ …         ┆ …         ┆ …          │
│ COM     ┆ 97613 ┆ 6   ┆ 976 ┆ … ┆ null     ┆ null      ┆ null      ┆ null       │
│ COM     ┆ 97614 ┆ 6   ┆ 976 ┆ … ┆ null     ┆ null      ┆ null      ┆ null       │
│ COM     ┆ 97615 ┆ 6   ┆ 976 ┆ … ┆ null     ┆ null      ┆ null      ┆ null       │
│ COM     ┆ 97616 ┆ 6   ┆ 976 ┆ … ┆ null     ┆ null      ┆ null      ┆ null       │
│ COM     ┆ 97617 ┆ 6   ┆ 976 ┆ … ┆ null     ┆ null      ┆ null      ┆ null       │
└─────────┴───────┴─────┴─────┴───┴──────────┴───────────┴───────────┴────────────┘

In [577]:
# Step 2: get election results
election_results = election_datasets.filter(pl.col("election_code") == election_code)
election_results = election_results[
    [
        s.name
        for s in election_results
        if not (s.null_count() == election_results.height)
    ]
]
election_results

shape: (35_326, 34)
┌─────┬────────────┬─────────────┬──────────────────────┬───┬─────────┬──────────┬──────────┬──────┐
│ dep ┆ nomdep     ┆ codecommune ┆ nomcommune           ┆ … ┆ pvoteTD ┆ pvoteGCG ┆ pvoteDCD ┆ pabs │
│ --- ┆ ---        ┆ ---         ┆ ---                  ┆   ┆ ---     ┆ ---      ┆ ---      ┆ ---  │
│ str ┆ str        ┆ str         ┆ str                  ┆   ┆ f64     ┆ f64      ┆ f64      ┆ f64  │
╞═════╪════════════╪═════════════╪══════════════════════╪═══╪═════════╪══════════╪══════════╪══════╡
│ 01  ┆ Ain        ┆ 01001       ┆ L'ABERGEMENT-CLÃMEN ┆ … ┆ 0.68    ┆ 0.2      ┆ 0.56     ┆ 0.15 │
│     ┆            ┆             ┆ CIAT                 ┆   ┆         ┆          ┆          ┆      │
│ 01  ┆ Ain        ┆ 01002       ┆ L'ABERGEMENT-DE-VARE ┆ … ┆ 0.61    ┆ 0.28     ┆ 0.51     ┆ 0.12 │
│     ┆            ┆             ┆ Y                    ┆   ┆         ┆          ┆          ┆      │
│ 01  ┆ Ain        ┆ 01004       ┆ AMBÃRIEU-EN-BUGEY   ┆ … ┆ 0.6     ┆ 0.3      ┆ 0.5      ┆ 0.23 │
│ 01  ┆ Ain        ┆ 01005       ┆ AMBÃRIEUX-EN-DOMBES ┆ … ┆ 0.7     ┆ 0.19     ┆ 0.6      ┆ 0.18 │
│ 01  ┆ Ain        ┆ 01006       ┆ AMBLÃON             ┆ … ┆ 0.57    ┆ 0.33     ┆ 0.47     ┆ 0.2  │
│ …   ┆ …          ┆ …           ┆ …                    ┆ … ┆ …       ┆ …        ┆ …        ┆ …    │
│ 95  ┆ Val-d'Oise ┆ 95676       ┆ VILLERS-EN-ARTHIES   ┆ … ┆ 0.69    ┆ 0.24     ┆ 0.62     ┆ 0.11 │
│ 95  ┆ Val-d'Oise ┆ 95678       ┆ VILLIERS-ADAM        ┆ … ┆ 0.66    ┆ 0.22     ┆ 0.55     ┆ 0.08 │
│ 95  ┆ Val-d'Oise ┆ 95680       ┆ VILLIERS-LE-BEL      ┆ … ┆ 0.44    ┆ 0.45     ┆ 0.33     ┆ 0.33 │
│ 95  ┆ Val-d'Oise ┆ 95682       ┆ VILLIERS-LE-SEC      ┆ … ┆ 0.55    ┆ 0.32     ┆ 0.43     ┆ 0.08 │
│ 95  ┆ Val-d'Oise ┆ 95690       ┆ WY-DIT-JOLI-VILLAGE  ┆ … ┆ 0.66    ┆ 0.2      ┆ 0.53     ┆ 0.15 │
└─────┴────────────┴─────────────┴──────────────────────┴───┴─────────┴──────────┴──────────┴──────┘

In [546]:
dataset = election_results.join(
    communes.select(
        "TYPECOM", "codecommune", "NCC", "NCCENR", "LIBELLE", "lat", "long"
    ),
    on="codecommune",
    how="left",
)
dataset = dataset.with_columns(
    lat=pl.col("lat").fill_null(pl.col("lat").mean().over("dep")),
    long=pl.col("long").fill_null(pl.col("long").mean().over("dep")),
)

In [547]:
# Step 3 : get relevant economic data
year = int(election_code[-4:])
X = get_features_for_years(
    socio_economic_data,
    year=year,
    feature_aug=["raw", "lag", "rank", "delta", "pct_change"],
    n_years_back=0,
)
X

shape: (44_644, 832)
┌──────┬────────────┬───────────┬───────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ year ┆ codecommun ┆ raw_age   ┆ raw_agef  ┆ … ┆ pct_change ┆ pct_change ┆ pct_change ┆ pct_chang │
│ ---  ┆ e          ┆ ---       ┆ ---       ┆   ┆ _electeurs ┆ _vbbm      ┆ _vbbmpauvr ┆ e_vbbmpau │
│ i64  ┆ ---        ┆ f64       ┆ f64       ┆   ┆ ---        ┆ ---        ┆ esriches   ┆ vresriche │
│      ┆ str        ┆           ┆           ┆   ┆ f64        ┆ f64        ┆ ---        ┆ sca…      │
│      ┆            ┆           ┆           ┆   ┆            ┆            ┆ f64        ┆ ---       │
│      ┆            ┆           ┆           ┆   ┆            ┆            ┆            ┆ f64       │
╞══════╪════════════╪═══════════╪═══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 2017 ┆ .          ┆ null      ┆ null      ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 2017 ┆ ..         ┆ null      ┆ null      ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 2017 ┆ ...        ┆ null      ┆ null      ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 2017 ┆ 01001      ┆ 41.607021 ┆ 41.094738 ┆ … ┆ 0.013037   ┆ 0.0        ┆ 0.0        ┆ 0.0       │
│ 2017 ┆ 01002      ┆ 38.197773 ┆ 34.541805 ┆ … ┆ 0.000794   ┆ 0.0        ┆ 0.0        ┆ 0.0       │
│ …    ┆ …          ┆ …         ┆ …         ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ 2017 ┆ 95Z001     ┆ null      ┆ null      ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 2017 ┆ 95Z002     ┆ null      ┆ null      ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 2017 ┆ 95Z003     ┆ null      ┆ null      ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 2017 ┆ ECOCHE     ┆ null      ┆ null      ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 2017 ┆ nan        ┆ null      ┆ null      ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
└──────┴────────────┴───────────┴───────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [548]:
dataset = dataset.join(X.drop("year"), on="codecommune", how="left")

In [549]:
dataset.sort("codecommune")

shape: (35_906, 870)
┌─────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ dep ┆ nomdep     ┆ codecommun ┆ nomcommune ┆ … ┆ pct_change ┆ pct_change ┆ pct_chang ┆ pct_chang │
│ --- ┆ ---        ┆ e          ┆ ---        ┆   ┆ _electeurs ┆ _vbbm      ┆ e_vbbmpau ┆ e_vbbmpau │
│ str ┆ str        ┆ ---        ┆ str        ┆   ┆ ---        ┆ ---        ┆ vresriche ┆ vresriche │
│     ┆            ┆ str        ┆            ┆   ┆ f64        ┆ f64        ┆ s         ┆ sca…      │
│     ┆            ┆            ┆            ┆   ┆            ┆            ┆ ---       ┆ ---       │
│     ┆            ┆            ┆            ┆   ┆            ┆            ┆ f64       ┆ f64       │
╞═════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 01  ┆ Ain        ┆ 01001      ┆ L'ABERGEME ┆ … ┆ 0.013037   ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ NT-CLÃMEN ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆            ┆ CIAT       ┆   ┆            ┆            ┆           ┆           │
│ 01  ┆ Ain        ┆ 01002      ┆ L'ABERGEME ┆ … ┆ 0.000794   ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ NT-DE-VARE ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆            ┆ Y          ┆   ┆            ┆            ┆           ┆           │
│ 01  ┆ Ain        ┆ 01004      ┆ AMBÃRIEU- ┆ … ┆ -0.003516  ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ EN-BUGEY   ┆   ┆            ┆            ┆           ┆           │
│ 01  ┆ Ain        ┆ 01005      ┆ AMBÃRIEUX ┆ … ┆ 0.020764   ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ -EN-DOMBES ┆   ┆            ┆            ┆           ┆           │
│ 01  ┆ Ain        ┆ 01006      ┆ AMBLÃON   ┆ … ┆ 0.022828   ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│ …   ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 95  ┆ Val-d'Oise ┆ 95676      ┆ VILLERS-EN ┆ … ┆ -0.013552  ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ -ARTHIES   ┆   ┆            ┆            ┆           ┆           │
│ 95  ┆ Val-d'Oise ┆ 95678      ┆ VILLIERS-A ┆ … ┆ 0.008609   ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ DAM        ┆   ┆            ┆            ┆           ┆           │
│ 95  ┆ Val-d'Oise ┆ 95680      ┆ VILLIERS-L ┆ … ┆ -0.001473  ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ E-BEL      ┆   ┆            ┆            ┆           ┆           │
│ 95  ┆ Val-d'Oise ┆ 95682      ┆ VILLIERS-L ┆ … ┆ 0.065716   ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ E-SEC      ┆   ┆            ┆            ┆           ┆           │
│ 95  ┆ Val-d'Oise ┆ 95690      ┆ WY-DIT-JOL ┆ … ┆ -0.020422  ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ I-VILLAGE  ┆   ┆            ┆            ┆           ┆           │
└─────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [550]:
dataset.null_count()

shape: (1, 870)
┌─────┬────────┬─────────────┬────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ dep ┆ nomdep ┆ codecommune ┆ nomcommune ┆ … ┆ pct_change_ ┆ pct_change ┆ pct_change ┆ pct_change │
│ --- ┆ ---    ┆ ---         ┆ ---        ┆   ┆ electeurs   ┆ _vbbm      ┆ _vbbmpauvr ┆ _vbbmpauvr │
│ u32 ┆ u32    ┆ u32         ┆ u32        ┆   ┆ ---         ┆ ---        ┆ esriches   ┆ esrichesca │
│     ┆        ┆             ┆            ┆   ┆ u32         ┆ u32        ┆ ---        ┆ …          │
│     ┆        ┆             ┆            ┆   ┆             ┆            ┆ u32        ┆ ---        │
│     ┆        ┆             ┆            ┆   ┆             ┆            ┆            ┆ u32        │
╞═════╪════════╪═════════════╪════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 0   ┆ 0      ┆ 0           ┆ 0          ┆ … ┆ 534         ┆ 480        ┆ 480        ┆ 480        │
└─────┴────────┴─────────────┴────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [551]:
threshold = 0.4

cols_to_keep = [s.name for s in dataset if s.null_count() / dataset.height < threshold]
cols_dropped = [s.name for s in dataset if s.null_count() / dataset.height >= threshold]

print(f"✅ Kept {len(cols_to_keep)} columns.")
print(f"❌ Dropped {len(cols_dropped)} columns (>= {int(threshold * 100)}% nulls):")
for col in cols_dropped:
    null_ratio = (
        dataset.null_count()[col][0] / dataset.height
    )  # note: already dropped, use original if needed
print(cols_dropped)
dataset = dataset[cols_to_keep]

✅ Kept 825 columns.
❌ Dropped 45 columns (>= 40% nulls):
['raw_misf', 'raw_mmoyfortune', 'raw_nfoyisf', 'raw_permisf', 'raw_perpisf', 'raw_pisf', 'lag_nfoyerrsa', 'lag_nrsa', 'lag_perrsa', 'lag_prsa', 'lag_misf', 'lag_mmoyfortune', 'lag_nfoyisf', 'lag_permisf', 'lag_perpisf', 'lag_pisf', 'rank_misf', 'rank_mmoyfortune', 'rank_nfoyisf', 'rank_permisf', 'rank_perpisf', 'rank_pisf', 'delta_nfoyerrsa', 'delta_nrsa', 'delta_perrsa', 'delta_prsa', 'delta_misf', 'delta_mmoyfortune', 'delta_nfoyisf', 'delta_permisf', 'delta_perpisf', 'delta_pisf', 'pct_change_agri', 'pct_change_pagri', 'pct_change_nfoyerrsa', 'pct_change_nrsa', 'pct_change_perrsa', 'pct_change_prsa', 'pct_change_propappartement', 'pct_change_misf', 'pct_change_mmoyfortune', 'pct_change_nfoyisf', 'pct_change_permisf', 'pct_change_perpisf', 'pct_change_pisf']

In [552]:
dataset.null_count()

shape: (1, 825)
┌─────┬────────┬─────────────┬────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ dep ┆ nomdep ┆ codecommune ┆ nomcommune ┆ … ┆ pct_change_ ┆ pct_change ┆ pct_change ┆ pct_change │
│ --- ┆ ---    ┆ ---         ┆ ---        ┆   ┆ electeurs   ┆ _vbbm      ┆ _vbbmpauvr ┆ _vbbmpauvr │
│ u32 ┆ u32    ┆ u32         ┆ u32        ┆   ┆ ---         ┆ ---        ┆ esriches   ┆ esrichesca │
│     ┆        ┆             ┆            ┆   ┆ u32         ┆ u32        ┆ ---        ┆ …          │
│     ┆        ┆             ┆            ┆   ┆             ┆            ┆ u32        ┆ ---        │
│     ┆        ┆             ┆            ┆   ┆             ┆            ┆            ┆ u32        │
╞═════╪════════╪═════════════╪════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 0   ┆ 0      ┆ 0           ┆ 0          ┆ … ┆ 534         ┆ 480        ┆ 480        ┆ 480        │
└─────┴────────┴─────────────┴────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [553]:
dataset.null_count().max_horizontal().item()

9987

In [554]:
null_counts = dataset.null_count()
max_val = null_counts.max_horizontal().item()

cols_with_max_nulls = [
    col
    for col, count in zip(null_counts.columns, null_counts.row(0))
    if count == max_val
]
print(cols_with_max_nulls)

['pct_change_pchom']

In [555]:
dataset.filter(pl.col("raw_age").is_null()).select(
    "pvoteG", "nomcommune", "codecommune", "raw_age"
).to_pandas().tail(100)

    pvoteG                  nomcommune codecommune  raw_age
0     0.15                   DOMMARTIN       01144      NaN
1     0.16                  LES COSTES       05043      NaN
2     0.20                   MONTMORIN       05088      NaN
3     0.17  SAINT-EUSÃBE-EN-CHAMPSAUR       05141      NaN
4     0.08                SAINTE-MARIE       05150      NaN
..     ...                         ...         ...      ...
91    0.19                SAINT-LUCIEN       76601      NaN
92    0.30                  BELLEVILLE       79033      NaN
93    0.24                BOISSEROLLES       79039      NaN
94    0.34    SAINT-ETIENNE-LA-CIGOGNE       79247      NaN
95    0.15                  GADANCOURT       95259      NaN

[96 rows x 4 columns]

In [556]:
meta_cols = [
    "dep",
    "nomdep",
    "codecommune",
    "nomcommune",
    "year",
    "type",
    "election_code",
    "inscrits",
    "votants",
    "exprimes",
    "voteG",
    "voteCG",
    "voteC",
    "voteCD",
    "voteD",
    "voteTG",
    "voteTD",
    "voteGCG",
    "voteDCD",
    "no_inscrits",
    "no_votants",
    "exprimes_",
    "ppar",
    "abstentions",
    "pvoteG",
    "pvoteCG",
    "pvoteC",
    "pvoteCD",
    "pvoteD",
    "pvoteTG",
    "pvoteTD",
    "pvoteGCG",
    "pvoteDCD",
    "pabs",
    "TYPECOM",
    "NCC",
    "NCCENR",
    "LIBELLE",
    "lat",
    "long",
]
features = [col for col in dataset.columns if col not in meta_cols]
print(features)

['raw_age', 'raw_agef', 'raw_ageh', 'raw_perage', 'raw_perprop014', 'raw_perprop60p', 'raw_perpropf', 'raw_pop', 'raw_popf', 'raw_popf014', 'raw_popf1539', 'raw_popf4059', 'raw_popf60p', 'raw_poph', 'raw_poph014', 'raw_poph1539', 'raw_poph4059', 'raw_poph60p', 'raw_prop014', 'raw_prop1539', 'raw_prop4059', 'raw_prop60p', 'raw_propf', 'raw_propf014', 'raw_propf1539', 'raw_propf4059', 'raw_propf60p', 'raw_agri', 'raw_aica', 'raw_aind', 'raw_cadr', 'raw_capi', 'raw_chom', 'raw_empl', 'raw_indp', 'raw_ouem', 'raw_ouvr', 'raw_pact', 'raw_pagri', 'raw_paica', 'raw_paind', 'raw_pcadr', 'raw_pcapi', 'raw_pchom', 'raw_pempl', 'raw_peragri', 'raw_peraica', 'raw_peraind', 'raw_percadr', 'raw_percapi', 'raw_perchom', 'raw_perempl', 'raw_perindp', 'raw_perouem', 'raw_perouvr', 'raw_perpint', 'raw_pindp', 'raw_pint', 'raw_pouem', 'raw_pouvr', 'raw_ppint', 'raw_nfoyerrsa', 'raw_nrsa', 'raw_perrsa', 'raw_prsa', 'raw_basefonciere', 'raw_basefonciereratio', 'raw_basefoncieretot', 'raw_basehabitation', 'raw_basehabitationratio', 'raw_basehabitationtot', 'raw_baseimpotslocaux', 'raw_baseimpotslocauxratio', 'raw_baseimpotslocauxtot', 'raw_recette', 'raw_recettefonciere', 'raw_recettefonciereratio', 'raw_recettefoncieretot', 'raw_recettehabitation', 'raw_recettehabitationratio', 'raw_recettehabitationtot', 'raw_recetteimpotslocaux', 'raw_recetteimpotslocauxratio', 'raw_recetteimpotslocauxtot', 'raw_recetteratio', 'raw_recettetot', 'raw_tauxfoncier', 'raw_tauxfoncierratio', 'raw_tauxhabitation', 'raw_tauxhabitationratio', 'raw_tauximpotslocaux', 'raw_tauximpotslocauxratio', 'raw_capitalimmo', 'raw_capitalimmoagglo', 'raw_capitalratio', 'raw_capitalratioagglo', 'raw_percap', 'raw_percapagglo', 'raw_prixbien', 'raw_prixm2', 'raw_prixm2ratio', 'raw_propappartement', 'raw_propappartementdep', 'raw_surface', 'raw_surfaceterrain', 'raw_bac', 'raw_bacf', 'raw_bach', 'raw_nodip', 'raw_nodipf', 'raw_nodiph', 'raw_pbac', 'raw_perbac', 'raw_persup', 'raw_psup', 'raw_sup', 'raw_supf', 'raw_suph', 'raw_etranger', 'raw_francais', 'raw_peretranger', 'raw_petranger', 'raw_immigre', 'raw_immnatur', 'raw_natur', 'raw_peretr', 'raw_perimmigre', 'raw_pimmigre', 'raw_pimmnatur', 'raw_pnatur', 'raw_pnaturfra', 'raw_nlogement', 'raw_npropri', 'raw_perpropri', 'raw_ppropri', 'raw_perpibratio', 'raw_pibratio', 'raw_pibtot', 'raw_nadult', 'raw_nfoyer', 'raw_perrev', 'raw_perrevadu', 'raw_perrevagglo', 'raw_perrevfoy', 'raw_revmoy', 'raw_revmoyadu', 'raw_revmoyfoy', 'raw_revratio', 'raw_revratioadu', 'raw_revratioagglo', 'raw_revratiofoy', 'raw_revtot', 'raw_revtotagglo', 'raw_peragglo', 'raw_percommu', 'raw_popagglo', 'raw_electeurs', 'raw_vbbm', 'raw_vbbmpauvresriches', 'raw_vbbmpauvresrichescap', 'lag_age', 'lag_agef', 'lag_ageh', 'lag_perage', 'lag_perprop014', 'lag_perprop60p', 'lag_perpropf', 'lag_pop', 'lag_popf', 'lag_popf014', 'lag_popf1539', 'lag_popf4059', 'lag_popf60p', 'lag_poph', 'lag_poph014', 'lag_poph1539', 'lag_poph4059', 'lag_poph60p', 'lag_prop014', 'lag_prop1539', 'lag_prop4059', 'lag_prop60p', 'lag_propf', 'lag_propf014', 'lag_propf1539', 'lag_propf4059', 'lag_propf60p', 'lag_agri', 'lag_aica', 'lag_aind', 'lag_cadr', 'lag_capi', 'lag_chom', 'lag_empl', 'lag_indp', 'lag_ouem', 'lag_ouvr', 'lag_pact', 'lag_pagri', 'lag_paica', 'lag_paind', 'lag_pcadr', 'lag_pcapi', 'lag_pchom', 'lag_pempl', 'lag_peragri', 'lag_peraica', 'lag_peraind', 'lag_percadr', 'lag_percapi', 'lag_perchom', 'lag_perempl', 'lag_perindp', 'lag_perouem', 'lag_perouvr', 'lag_perpint', 'lag_pindp', 'lag_pint', 'lag_pouem', 'lag_pouvr', 'lag_ppint', 'lag_basefonciere', 'lag_basefonciereratio', 'lag_basefoncieretot', 'lag_basehabitation', 'lag_basehabitationratio', 'lag_basehabitationtot', 'lag_baseimpotslocaux', 'lag_baseimpotslocauxratio', 'lag_baseimpotslocauxtot', 'lag_recette', 'lag_recettefonciere', 'lag_recettefonciereratio', 'lag_recettefoncieretot', 'lag_recettehabitation', 'lag_recettehabitationratio', 'lag_recettehabitationtot', 'lag_recetteimpotslocaux', 'lag_recetteimpotslocauxratio', 'lag_recetteimpotslocauxtot', 'lag_recetteratio', 'lag_recettetot', 'lag_tauxfoncier', 'lag_tauxfoncierratio', 'lag_tauxhabitation', 'lag_tauxhabitationratio', 'lag_tauximpotslocaux', 'lag_tauximpotslocauxratio', 'lag_capitalimmo', 'lag_capitalimmoagglo', 'lag_capitalratio', 'lag_capitalratioagglo', 'lag_percap', 'lag_percapagglo', 'lag_prixbien', 'lag_prixm2', 'lag_prixm2ratio', 'lag_propappartement', 'lag_propappartementdep', 'lag_surface', 'lag_surfaceterrain', 'lag_bac', 'lag_bacf', 'lag_bach', 'lag_nodip', 'lag_nodipf', 'lag_nodiph', 'lag_pbac', 'lag_perbac', 'lag_persup', 'lag_psup', 'lag_sup', 'lag_supf', 'lag_suph', 'lag_etranger', 'lag_francais', 'lag_peretranger', 'lag_petranger', 'lag_immigre', 'lag_immnatur', 'lag_natur', 'lag_peretr', 'lag_perimmigre', 'lag_pimmigre', 'lag_pimmnatur', 'lag_pnatur', 'lag_pnaturfra', 'lag_nlogement', 'lag_npropri', 'lag_perpropri', 'lag_ppropri', 'lag_perpibratio', 'lag_pibratio', 'lag_pibtot', 'lag_nadult', 'lag_nfoyer', 'lag_perrev', 'lag_perrevadu', 'lag_perrevagglo', 'lag_perrevfoy', 'lag_revmoy', 'lag_revmoyadu', 'lag_revmoyfoy', 'lag_revratio', 'lag_revratioadu', 'lag_revratioagglo', 'lag_revratiofoy', 'lag_revtot', 'lag_revtotagglo', 'lag_peragglo', 'lag_percommu', 'lag_popagglo', 'lag_electeurs', 'lag_vbbm', 'lag_vbbmpauvresriches', 'lag_vbbmpauvresrichescap', 'rank_age', 'rank_agef', 'rank_ageh', 'rank_perage', 'rank_perprop014', 'rank_perprop60p', 'rank_perpropf', 'rank_pop', 'rank_popf', 'rank_popf014', 'rank_popf1539', 'rank_popf4059', 'rank_popf60p', 'rank_poph', 'rank_poph014', 'rank_poph1539', 'rank_poph4059', 'rank_poph60p', 'rank_prop014', 'rank_prop1539', 'rank_prop4059', 'rank_prop60p', 'rank_propf', 'rank_propf014', 'rank_propf1539', 'rank_propf4059', 'rank_propf60p', 'rank_agri', 'rank_aica', 'rank_aind', 'rank_cadr', 'rank_capi', 'rank_chom', 'rank_empl', 'rank_indp', 'rank_ouem', 'rank_ouvr', 'rank_pact', 'rank_pagri', 'rank_paica', 'rank_paind', 'rank_pcadr', 'rank_pcapi', 'rank_pchom', 'rank_pempl', 'rank_peragri', 'rank_peraica', 'rank_peraind', 'rank_percadr', 'rank_percapi', 'rank_perchom', 'rank_perempl', 'rank_perindp', 'rank_perouem', 'rank_perouvr', 'rank_perpint', 'rank_pindp', 'rank_pint', 'rank_pouem', 'rank_pouvr', 'rank_ppint', 'rank_nfoyerrsa', 'rank_nrsa', 'rank_perrsa', 'rank_prsa', 'rank_basefonciere', 'rank_basefonciereratio', 'rank_basefoncieretot', 'rank_basehabitation', 'rank_basehabitationratio', 'rank_basehabitationtot', 'rank_baseimpotslocaux', 'rank_baseimpotslocauxratio', 'rank_baseimpotslocauxtot', 'rank_recette', 'rank_recettefonciere', 'rank_recettefonciereratio', 'rank_recettefoncieretot', 'rank_recettehabitation', 'rank_recettehabitationratio', 'rank_recettehabitationtot', 'rank_recetteimpotslocaux', 'rank_recetteimpotslocauxratio', 'rank_recetteimpotslocauxtot', 'rank_recetteratio', 'rank_recettetot', 'rank_tauxfoncier', 'rank_tauxfoncierratio', 'rank_tauxhabitation', 'rank_tauxhabitationratio', 'rank_tauximpotslocaux', 'rank_tauximpotslocauxratio', 'rank_capitalimmo', 'rank_capitalimmoagglo', 'rank_capitalratio', 'rank_capitalratioagglo', 'rank_percap', 'rank_percapagglo', 'rank_prixbien', 'rank_prixm2', 'rank_prixm2ratio', 'rank_propappartement', 'rank_propappartementdep', 'rank_surface', 'rank_surfaceterrain', 'rank_bac', 'rank_bacf', 'rank_bach', 'rank_nodip', 'rank_nodipf', 'rank_nodiph', 'rank_pbac', 'rank_perbac', 'rank_persup', 'rank_psup', 'rank_sup', 'rank_supf', 'rank_suph', 'rank_etranger', 'rank_francais', 'rank_peretranger', 'rank_petranger', 'rank_immigre', 'rank_immnatur', 'rank_natur', 'rank_peretr', 'rank_perimmigre', 'rank_pimmigre', 'rank_pimmnatur', 'rank_pnatur', 'rank_pnaturfra', 'rank_nlogement', 'rank_npropri', 'rank_perpropri', 'rank_ppropri', 'rank_perpibratio', 'rank_pibratio', 'rank_pibtot', 'rank_nadult', 'rank_nfoyer', 'rank_perrev', 'rank_perrevadu', 'rank_perrevagglo', 'rank_perrevfoy', 'rank_revmoy', 'rank_revmoyadu', 'rank_revmoyfoy', 'rank_revratio', 'rank_revratioadu', 'rank_revratioagglo', 'rank_revratiofoy', 'rank_revtot', 'rank_revtotagglo', 'rank_peragglo', 'rank_percommu', 'rank_popagglo', 'rank_electeurs', 'rank_vbbm', 'rank_vbbmpauvresriches', 'rank_vbbmpauvresrichescap', 'delta_age', 'delta_agef', 'delta_ageh', 'delta_perage', 'delta_perprop014', 'delta_perprop60p', 'delta_perpropf', 'delta_pop', 'delta_popf', 'delta_popf014', 'delta_popf1539', 'delta_popf4059', 'delta_popf60p', 'delta_poph', 'delta_poph014', 'delta_poph1539', 'delta_poph4059', 'delta_poph60p', 'delta_prop014', 'delta_prop1539', 'delta_prop4059', 'delta_prop60p', 'delta_propf', 'delta_propf014', 'delta_propf1539', 'delta_propf4059', 'delta_propf60p', 'delta_agri', 'delta_aica', 'delta_aind', 'delta_cadr', 'delta_capi', 'delta_chom', 'delta_empl', 'delta_indp', 'delta_ouem', 'delta_ouvr', 'delta_pact', 'delta_pagri', 'delta_paica', 'delta_paind', 'delta_pcadr', 'delta_pcapi', 'delta_pchom', 'delta_pempl', 'delta_peragri', 'delta_peraica', 'delta_peraind', 'delta_percadr', 'delta_percapi', 'delta_perchom', 'delta_perempl', 'delta_perindp', 'delta_perouem', 'delta_perouvr', 'delta_perpint', 'delta_pindp', 'delta_pint', 'delta_pouem', 'delta_pouvr', 'delta_ppint', 'delta_basefonciere', 'delta_basefonciereratio', 'delta_basefoncieretot', 'delta_basehabitation', 'delta_basehabitationratio', 'delta_basehabitationtot', 'delta_baseimpotslocaux', 'delta_baseimpotslocauxratio', 'delta_baseimpotslocauxtot', 'delta_recette', 'delta_recettefonciere', 'delta_recettefonciereratio', 'delta_recettefoncieretot', 'delta_recettehabitation', 'delta_recettehabitationratio', 'delta_recettehabitationtot', 'delta_recetteimpotslocaux', 'delta_recetteimpotslocauxratio', 'delta_recetteimpotslocauxtot', 'delta_recetteratio', 'delta_recettetot', 'delta_tauxfoncier', 'delta_tauxfoncierratio', 'delta_tauxhabitation', 'delta_tauxhabitationratio', 'delta_tauximpotslocaux', 'delta_tauximpotslocauxratio', 'delta_capitalimmo', 'delta_capitalimmoagglo', 'delta_capitalratio', 'delta_capitalratioagglo', 'delta_percap', 'delta_percapagglo', 'delta_prixbien', 'delta_prixm2', 'delta_prixm2ratio', 'delta_propappartement', 'delta_propappartementdep', 'delta_surface', 'delta_surfaceterrain', 'delta_bac', 'delta_bacf', 'delta_bach', 'delta_nodip', 'delta_nodipf', 'delta_nodiph', 'delta_pbac', 'delta_perbac', 'delta_persup', 'delta_psup', 'delta_sup', 'delta_supf', 'delta_suph', 'delta_etranger', 'delta_francais', 'delta_peretranger', 'delta_petranger', 'delta_immigre', 'delta_immnatur', 'delta_natur', 'delta_peretr', 'delta_perimmigre', 'delta_pimmigre', 'delta_pimmnatur', 'delta_pnatur', 'delta_pnaturfra', 'delta_nlogement', 'delta_npropri', 'delta_perpropri', 'delta_ppropri', 'delta_perpibratio', 'delta_pibratio', 'delta_pibtot', 'delta_nadult', 'delta_nfoyer', 'delta_perrev', 'delta_perrevadu', 'delta_perrevagglo', 'delta_perrevfoy', 'delta_revmoy', 'delta_revmoyadu', 'delta_revmoyfoy', 'delta_revratio', 'delta_revratioadu', 'delta_revratioagglo', 'delta_revratiofoy', 'delta_revtot', 'delta_revtotagglo', 'delta_peragglo', 'delta_percommu', 'delta_popagglo', 'delta_electeurs', 'delta_vbbm', 'delta_vbbmpauvresriches', 'delta_vbbmpauvresrichescap', 'pct_change_age', 'pct_change_agef', 'pct_change_ageh', 'pct_change_perage', 'pct_change_perprop014', 'pct_change_perprop60p', 'pct_change_perpropf', 'pct_change_pop', 'pct_change_popf', 'pct_change_popf014', 'pct_change_popf1539', 'pct_change_popf4059', 'pct_change_popf60p', 'pct_change_poph', 'pct_change_poph014', 'pct_change_poph1539', 'pct_change_poph4059', 'pct_change_poph60p', 'pct_change_prop014', 'pct_change_prop1539', 'pct_change_prop4059', 'pct_change_prop60p', 'pct_change_propf', 'pct_change_propf014', 'pct_change_propf1539', 'pct_change_propf4059', 'pct_change_propf60p', 'pct_change_aica', 'pct_change_aind', 'pct_change_cadr', 'pct_change_capi', 'pct_change_chom', 'pct_change_empl', 'pct_change_indp', 'pct_change_ouem', 'pct_change_ouvr', 'pct_change_pact', 'pct_change_paica', 'pct_change_paind', 'pct_change_pcadr', 'pct_change_pcapi', 'pct_change_pchom', 'pct_change_pempl', 'pct_change_peragri', 'pct_change_peraica', 'pct_change_peraind', 'pct_change_percadr', 'pct_change_percapi', 'pct_change_perchom', 'pct_change_perempl', 'pct_change_perindp', 'pct_change_perouem', 'pct_change_perouvr', 'pct_change_perpint', 'pct_change_pindp', 'pct_change_pint', 'pct_change_pouem', 'pct_change_pouvr', 'pct_change_ppint', 'pct_change_basefonciere', 'pct_change_basefonciereratio', 'pct_change_basefoncieretot', 'pct_change_basehabitation', 'pct_change_basehabitationratio', 'pct_change_basehabitationtot', 'pct_change_baseimpotslocaux', 'pct_change_baseimpotslocauxratio', 'pct_change_baseimpotslocauxtot', 'pct_change_recette', 'pct_change_recettefonciere', 'pct_change_recettefonciereratio', 'pct_change_recettefoncieretot', 'pct_change_recettehabitation', 'pct_change_recettehabitationratio', 'pct_change_recettehabitationtot', 'pct_change_recetteimpotslocaux', 'pct_change_recetteimpotslocauxratio', 'pct_change_recetteimpotslocauxtot', 'pct_change_recetteratio', 'pct_change_recettetot', 'pct_change_tauxfoncier', 'pct_change_tauxfoncierratio', 'pct_change_tauxhabitation', 'pct_change_tauxhabitationratio', 'pct_change_tauximpotslocaux', 'pct_change_tauximpotslocauxratio', 'pct_change_capitalimmo', 'pct_change_capitalimmoagglo', 'pct_change_capitalratio', 'pct_change_capitalratioagglo', 'pct_change_percap', 'pct_change_percapagglo', 'pct_change_prixbien', 'pct_change_prixm2', 'pct_change_prixm2ratio', 'pct_change_propappartementdep', 'pct_change_surface', 'pct_change_surfaceterrain', 'pct_change_bac', 'pct_change_bacf', 'pct_change_bach', 'pct_change_nodip', 'pct_change_nodipf', 'pct_change_nodiph', 'pct_change_pbac', 'pct_change_perbac', 'pct_change_persup', 'pct_change_psup', 'pct_change_sup', 'pct_change_supf', 'pct_change_suph', 'pct_change_etranger', 'pct_change_francais', 'pct_change_peretranger', 'pct_change_petranger', 'pct_change_immigre', 'pct_change_immnatur', 'pct_change_natur', 'pct_change_peretr', 'pct_change_perimmigre', 'pct_change_pimmigre', 'pct_change_pimmnatur', 'pct_change_pnatur', 'pct_change_pnaturfra', 'pct_change_nlogement', 'pct_change_npropri', 'pct_change_perpropri', 'pct_change_ppropri', 'pct_change_perpibratio', 'pct_change_pibratio', 'pct_change_pibtot', 'pct_change_nadult', 'pct_change_nfoyer', 'pct_change_perrev', 'pct_change_perrevadu', 'pct_change_perrevagglo', 'pct_change_perrevfoy', 'pct_change_revmoy', 'pct_change_revmoyadu', 'pct_change_revmoyfoy', 'pct_change_revratio', 'pct_change_revratioadu', 'pct_change_revratioagglo', 'pct_change_revratiofoy', 'pct_change_revtot', 'pct_change_revtotagglo', 'pct_change_peragglo', 'pct_change_percommu', 'pct_change_popagglo', 'pct_change_electeurs', 'pct_change_vbbm', 'pct_change_vbbmpauvresriches', 'pct_change_vbbmpauvresrichescap']

In [557]:
dataset

shape: (35_906, 825)
┌─────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ dep ┆ nomdep     ┆ codecommun ┆ nomcommune ┆ … ┆ pct_change ┆ pct_change ┆ pct_chang ┆ pct_chang │
│ --- ┆ ---        ┆ e          ┆ ---        ┆   ┆ _electeurs ┆ _vbbm      ┆ e_vbbmpau ┆ e_vbbmpau │
│ str ┆ str        ┆ ---        ┆ str        ┆   ┆ ---        ┆ ---        ┆ vresriche ┆ vresriche │
│     ┆            ┆ str        ┆            ┆   ┆ f64        ┆ f64        ┆ s         ┆ sca…      │
│     ┆            ┆            ┆            ┆   ┆            ┆            ┆ ---       ┆ ---       │
│     ┆            ┆            ┆            ┆   ┆            ┆            ┆ f64       ┆ f64       │
╞═════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 01  ┆ Ain        ┆ 01001      ┆ L'ABERGEME ┆ … ┆ 0.013037   ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ NT-CLÃMEN ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆            ┆ CIAT       ┆   ┆            ┆            ┆           ┆           │
│ 01  ┆ Ain        ┆ 01002      ┆ L'ABERGEME ┆ … ┆ 0.000794   ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ NT-DE-VARE ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆            ┆ Y          ┆   ┆            ┆            ┆           ┆           │
│ 01  ┆ Ain        ┆ 01004      ┆ AMBÃRIEU- ┆ … ┆ -0.003516  ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ EN-BUGEY   ┆   ┆            ┆            ┆           ┆           │
│ 01  ┆ Ain        ┆ 01005      ┆ AMBÃRIEUX ┆ … ┆ 0.020764   ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ -EN-DOMBES ┆   ┆            ┆            ┆           ┆           │
│ 01  ┆ Ain        ┆ 01006      ┆ AMBLÃON   ┆ … ┆ 0.022828   ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│ …   ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 95  ┆ Val-d'Oise ┆ 95676      ┆ VILLERS-EN ┆ … ┆ -0.013552  ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ -ARTHIES   ┆   ┆            ┆            ┆           ┆           │
│ 95  ┆ Val-d'Oise ┆ 95678      ┆ VILLIERS-A ┆ … ┆ 0.008609   ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ DAM        ┆   ┆            ┆            ┆           ┆           │
│ 95  ┆ Val-d'Oise ┆ 95680      ┆ VILLIERS-L ┆ … ┆ -0.001473  ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ E-BEL      ┆   ┆            ┆            ┆           ┆           │
│ 95  ┆ Val-d'Oise ┆ 95682      ┆ VILLIERS-L ┆ … ┆ 0.065716   ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ E-SEC      ┆   ┆            ┆            ┆           ┆           │
│ 95  ┆ Val-d'Oise ┆ 95690      ┆ WY-DIT-JOL ┆ … ┆ -0.020422  ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ I-VILLAGE  ┆   ┆            ┆            ┆           ┆           │
└─────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [558]:
dataset = dataset.with_columns(
    [
        pl.col(c)
        .fill_null(pl.col(c).mean().over("dep"))
        .fill_null(pl.col(c).mean())  # Fallback to all
        .alias(c)
        for c in features
    ]
)

In [559]:
# We need to remove col with no variation

# Compute std for all feature columns
std_df = dataset.select(features).std()

# Find columns with variation (std > 0 and not null)
cols_with_variation = [
    col
    for col, std_val in zip(std_df.columns, std_df.row(0))
    if std_val is not None and std_val > 0
]

# Report dropped columns
cols_dropped = [
    col
    for col, std_val in zip(std_df.columns, std_df.row(0))
    if std_val is None or std_val == 0
]

print(f"✅ Kept {len(cols_with_variation)} columns with variation.")
print(f"❌ Dropped {len(cols_dropped)} columns with no variation (std == 0 or null):")
for col in cols_dropped:
    print(f"   - {col}")

# Apply the filter
dataset = dataset.select(meta_cols + cols_with_variation)

✅ Kept 785 columns with variation.
❌ Dropped 0 columns with no variation (std == 0 or null):

In [560]:
data_quality_checks(dataset.drop(cs.string() | cs.boolean()))

NaN
shape: (1, 813)
┌──────┬──────────┬─────────┬──────────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ year ┆ inscrits ┆ votants ┆ exprimes ┆ … ┆ pct_change_ ┆ pct_change_ ┆ pct_change_ ┆ pct_change_ │
│ ---  ┆ ---      ┆ ---     ┆ ---      ┆   ┆ electeurs   ┆ vbbm        ┆ vbbmpauvres ┆ vbbmpauvres │
│ u32  ┆ u32      ┆ u32     ┆ u32      ┆   ┆ ---         ┆ ---         ┆ riches      ┆ richesca…   │
│      ┆          ┆         ┆          ┆   ┆ u32         ┆ u32         ┆ ---         ┆ ---         │
│      ┆          ┆         ┆          ┆   ┆             ┆             ┆ u32         ┆ u32         │
╞══════╪══════════╪═════════╪══════════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 0    ┆ 0        ┆ 0       ┆ 0        ┆ … ┆ 0           ┆ 0           ┆ 0           ┆ 0           │
└──────┴──────────┴─────────┴──────────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘
0
Null
shape: (1, 813)
┌──────┬──────────┬─────────┬──────────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ year ┆ inscrits ┆ votants ┆ exprimes ┆ … ┆ pct_change_ ┆ pct_change_ ┆ pct_change_ ┆ pct_change_ │
│ ---  ┆ ---      ┆ ---     ┆ ---      ┆   ┆ electeurs   ┆ vbbm        ┆ vbbmpauvres ┆ vbbmpauvres │
│ u32  ┆ u32      ┆ u32     ┆ u32      ┆   ┆ ---         ┆ ---         ┆ riches      ┆ richesca…   │
│      ┆          ┆         ┆          ┆   ┆ u32         ┆ u32         ┆ ---         ┆ ---         │
│      ┆          ┆         ┆          ┆   ┆             ┆             ┆ u32         ┆ u32         │
╞══════╪══════════╪═════════╪══════════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 0    ┆ 0        ┆ 0       ┆ 0        ┆ … ┆ 0           ┆ 0           ┆ 0           ┆ 0           │
└──────┴──────────┴─────────┴──────────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘
0
Inf
shape: (1, 813)
┌──────┬──────────┬─────────┬──────────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ year ┆ inscrits ┆ votants ┆ exprimes ┆ … ┆ pct_change_ ┆ pct_change_ ┆ pct_change_ ┆ pct_change_ │
│ ---  ┆ ---      ┆ ---     ┆ ---      ┆   ┆ electeurs   ┆ vbbm        ┆ vbbmpauvres ┆ vbbmpauvres │
│ u32  ┆ u32      ┆ u32     ┆ u32      ┆   ┆ ---         ┆ ---         ┆ riches      ┆ richesca…   │
│      ┆          ┆         ┆          ┆   ┆ u32         ┆ u32         ┆ ---         ┆ ---         │
│      ┆          ┆         ┆          ┆   ┆             ┆             ┆ u32         ┆ u32         │
╞══════╪══════════╪═════════╪══════════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 0    ┆ 0        ┆ 0       ┆ 0        ┆ … ┆ 0           ┆ 0           ┆ 0           ┆ 0           │
└──────┴──────────┴─────────┴──────────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘
0

In [561]:
dataset.null_count().max_horizontal()

shape: (1,)
Series: 'max' [u32]
[
	114
]

In [562]:
null_counts = dataset.null_count()
max_val = null_counts.max_horizontal().item()

cols_with_max_nulls = [
    col
    for col, count in zip(null_counts.columns, null_counts.row(0))
    if count == max_val
]
print(cols_with_max_nulls)

['TYPECOM', 'NCC', 'NCCENR', 'LIBELLE']

In [ ]:
# dataset.write_csv('Y.csv')

In [567]:
dataset

shape: (35_906, 825)
┌─────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ dep ┆ nomdep     ┆ codecommun ┆ nomcommune ┆ … ┆ pct_change ┆ pct_change ┆ pct_chang ┆ pct_chang │
│ --- ┆ ---        ┆ e          ┆ ---        ┆   ┆ _electeurs ┆ _vbbm      ┆ e_vbbmpau ┆ e_vbbmpau │
│ str ┆ str        ┆ ---        ┆ str        ┆   ┆ ---        ┆ ---        ┆ vresriche ┆ vresriche │
│     ┆            ┆ str        ┆            ┆   ┆ f64        ┆ f64        ┆ s         ┆ sca…      │
│     ┆            ┆            ┆            ┆   ┆            ┆            ┆ ---       ┆ ---       │
│     ┆            ┆            ┆            ┆   ┆            ┆            ┆ f64       ┆ f64       │
╞═════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 01  ┆ Ain        ┆ 01001      ┆ L'ABERGEME ┆ … ┆ 0.013037   ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ NT-CLÃMEN ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆            ┆ CIAT       ┆   ┆            ┆            ┆           ┆           │
│ 01  ┆ Ain        ┆ 01002      ┆ L'ABERGEME ┆ … ┆ 0.000794   ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ NT-DE-VARE ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆            ┆ Y          ┆   ┆            ┆            ┆           ┆           │
│ 01  ┆ Ain        ┆ 01004      ┆ AMBÃRIEU- ┆ … ┆ -0.003516  ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ EN-BUGEY   ┆   ┆            ┆            ┆           ┆           │
│ 01  ┆ Ain        ┆ 01005      ┆ AMBÃRIEUX ┆ … ┆ 0.020764   ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ -EN-DOMBES ┆   ┆            ┆            ┆           ┆           │
│ 01  ┆ Ain        ┆ 01006      ┆ AMBLÃON   ┆ … ┆ 0.022828   ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│ …   ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 95  ┆ Val-d'Oise ┆ 95676      ┆ VILLERS-EN ┆ … ┆ -0.013552  ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ -ARTHIES   ┆   ┆            ┆            ┆           ┆           │
│ 95  ┆ Val-d'Oise ┆ 95678      ┆ VILLIERS-A ┆ … ┆ 0.008609   ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ DAM        ┆   ┆            ┆            ┆           ┆           │
│ 95  ┆ Val-d'Oise ┆ 95680      ┆ VILLIERS-L ┆ … ┆ -0.001473  ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ E-BEL      ┆   ┆            ┆            ┆           ┆           │
│ 95  ┆ Val-d'Oise ┆ 95682      ┆ VILLIERS-L ┆ … ┆ 0.065716   ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ E-SEC      ┆   ┆            ┆            ┆           ┆           │
│ 95  ┆ Val-d'Oise ┆ 95690      ┆ WY-DIT-JOL ┆ … ┆ -0.020422  ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│     ┆            ┆            ┆ I-VILLAGE  ┆   ┆            ┆            ┆           ┆           │
└─────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

1. Handle PLM — responsible for a lot of nulls
2. (Drop columns based on a threshold)
3. Input with the departemental mean (local mean)

Handle features not available for all years (merge with pivot of previous years?)

## Stacking

In [566]:
X = pl.scan_csv("X.csv", infer_schema_length=40000).collect()
Y = pl.scan_csv("Y.csv", infer_schema_length=40000).collect()

In [573]:
set(X.columns) - set(Y.columns)

set()

In [574]:
set(Y.columns) - set(X.columns)

{'delta_basefonciere',
 'delta_basefonciereratio',
 'delta_basefoncieretot',
 'delta_basehabitation',
 'delta_basehabitationratio',
 'delta_basehabitationtot',
 'delta_baseimpotslocaux',
 'delta_baseimpotslocauxratio',
 'delta_baseimpotslocauxtot',
 'delta_nfoyer',
 'delta_perrevfoy',
 'delta_recette',
 'delta_recettefonciere',
 'delta_recettefonciereratio',
 'delta_recettefoncieretot',
 'delta_recettehabitation',
 'delta_recettehabitationratio',
 'delta_recettehabitationtot',
 'delta_recetteimpotslocaux',
 'delta_recetteimpotslocauxratio',
 'delta_recetteimpotslocauxtot',
 'delta_recetteratio',
 'delta_recettetot',
 'delta_revmoyfoy',
 'delta_revratiofoy',
 'delta_revtot',
 'delta_revtotagglo',
 'delta_tauxfoncier',
 'delta_tauxfoncierratio',
 'delta_tauxhabitation',
 'delta_tauxhabitationratio',
 'delta_tauximpotslocaux',
 'delta_tauximpotslocauxratio',
 'lag_basefonciere',
 'lag_basefonciereratio',
 'lag_basefoncieretot',
 'lag_basehabitation',
 'lag_basehabitationratio',
 'lag_basehabitationtot',
 'lag_baseimpotslocaux',
 'lag_baseimpotslocauxratio',
 'lag_baseimpotslocauxtot',
 'lag_recette',
 'lag_recettefonciere',
 'lag_recettefonciereratio',
 'lag_recettefoncieretot',
 'lag_recettehabitation',
 'lag_recettehabitationratio',
 'lag_recettehabitationtot',
 'lag_recetteimpotslocaux',
 'lag_recetteimpotslocauxtot',
 'lag_recettetot',
 'lag_tauxfoncier',
 'lag_tauxfoncierratio',
 'lag_tauxhabitation',
 'lag_tauxhabitationratio',
 'lag_tauximpotslocaux',
 'lag_tauximpotslocauxratio',
 'pct_change_basefonciere',
 'pct_change_basefonciereratio',
 'pct_change_basefoncieretot',
 'pct_change_basehabitation',
 'pct_change_basehabitationratio',
 'pct_change_basehabitationtot',
 'pct_change_baseimpotslocaux',
 'pct_change_baseimpotslocauxratio',
 'pct_change_baseimpotslocauxtot',
 'pct_change_nfoyer',
 'pct_change_perrevfoy',
 'pct_change_recette',
 'pct_change_recettefonciere',
 'pct_change_recettefonciereratio',
 'pct_change_recettefoncieretot',
 'pct_change_recettehabitation',
 'pct_change_recettehabitationratio',
 'pct_change_recettehabitationtot',
 'pct_change_recetteimpotslocaux',
 'pct_change_recetteimpotslocauxratio',
 'pct_change_recetteimpotslocauxtot',
 'pct_change_recetteratio',
 'pct_change_recettetot',
 'pct_change_revmoyfoy',
 'pct_change_revratiofoy',
 'pct_change_revtot',
 'pct_change_revtotagglo',
 'pct_change_tauxfoncier',
 'pct_change_tauxfoncierratio',
 'pct_change_tauxhabitation',
 'pct_change_tauxhabitationratio',
 'pct_change_tauximpotslocaux',
 'pct_change_tauximpotslocauxratio',
 'rank_basefonciere',
 'rank_basefonciereratio',
 'rank_basefoncieretot',
 'rank_basehabitation',
 'rank_basehabitationratio',
 'rank_basehabitationtot',
 'rank_baseimpotslocaux',
 'rank_baseimpotslocauxratio',
 'rank_baseimpotslocauxtot',
 'rank_nfoyerrsa',
 'rank_nrsa',
 'rank_perrsa',
 'rank_prsa',
 'rank_recette',
 'rank_recettefonciere',
 'rank_recettefonciereratio',
 'rank_recettefoncieretot',
 'rank_recettehabitation',
 'rank_recettehabitationratio',
 'rank_recettehabitationtot',
 'rank_recetteimpotslocaux',
 'rank_recetteimpotslocauxtot',
 'rank_recettetot',
 'rank_tauxfoncier',
 'rank_tauxfoncierratio',
 'rank_tauxhabitation',
 'rank_tauxhabitationratio',
 'rank_tauximpotslocaux',
 'rank_tauximpotslocauxratio',
 'raw_basefonciere',
 'raw_basefonciereratio',
 'raw_basefoncieretot',
 'raw_basehabitation',
 'raw_basehabitationratio',
 'raw_basehabitationtot',
 'raw_baseimpotslocaux',
 'raw_baseimpotslocauxratio',
 'raw_baseimpotslocauxtot',
 'raw_nfoyerrsa',
 'raw_nrsa',
 'raw_perrsa',
 'raw_prsa',
 'raw_recette',
 'raw_recettefonciere',
 'raw_recettefonciereratio',
 'raw_recettefoncieretot',
 'raw_recettehabitation',
 'raw_recettehabitationratio',
 'raw_recettehabitationtot',
 'raw_recetteimpotslocaux',
 'raw_recetteimpotslocauxtot',
 'raw_recettetot',
 'raw_tauxfoncier',
 'raw_tauxfoncierratio',
 'raw_tauxhabitation',
 'raw_tauxhabitationratio',
 'raw_tauximpotslocaux',
 'raw_tauximpotslocauxratio'}

In [572]:
len(set(X.columns).intersection(set(Y.columns)))

676

In [575]:
result = pl.concat([X, Y], how="diagonal")

In [576]:
result

shape: (71_351, 825)
┌─────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ dep ┆ nomdep     ┆ codecommun ┆ nomcommune ┆ … ┆ pct_change ┆ pct_change ┆ pct_chang ┆ pct_chang │
│ --- ┆ ---        ┆ e          ┆ ---        ┆   ┆ _revmoyfoy ┆ _revratiof ┆ e_revtot  ┆ e_revtota │
│ str ┆ str        ┆ ---        ┆ str        ┆   ┆ ---        ┆ oy         ┆ ---       ┆ gglo      │
│     ┆            ┆ str        ┆            ┆   ┆ f64        ┆ ---        ┆ f64       ┆ ---       │
│     ┆            ┆            ┆            ┆   ┆            ┆ f64        ┆           ┆ f64       │
╞═════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 01  ┆ Ain        ┆ 01001      ┆ L'ABERGEME ┆ … ┆ null       ┆ null       ┆ null      ┆ null      │
│     ┆            ┆            ┆ NT-CLÃMEN ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆            ┆ CIAT       ┆   ┆            ┆            ┆           ┆           │
│ 01  ┆ Ain        ┆ 01002      ┆ L'ABERGEME ┆ … ┆ null       ┆ null       ┆ null      ┆ null      │
│     ┆            ┆            ┆ NT-DE-VARE ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆            ┆ Y          ┆   ┆            ┆            ┆           ┆           │
│ 01  ┆ Ain        ┆ 01004      ┆ AMBÃRIEU- ┆ … ┆ null       ┆ null       ┆ null      ┆ null      │
│     ┆            ┆            ┆ EN-BUGEY   ┆   ┆            ┆            ┆           ┆           │
│ 01  ┆ Ain        ┆ 01005      ┆ AMBÃRIEUX ┆ … ┆ null       ┆ null       ┆ null      ┆ null      │
│     ┆            ┆            ┆ -EN-DOMBES ┆   ┆            ┆            ┆           ┆           │
│ 01  ┆ Ain        ┆ 01006      ┆ AMBLÃON   ┆ … ┆ null       ┆ null       ┆ null      ┆ null      │
│ …   ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 95  ┆ Val-d'Oise ┆ 95676      ┆ VILLERS-EN ┆ … ┆ -0.012171  ┆ -0.020851  ┆ -0.04557  ┆ -0.04557  │
│     ┆            ┆            ┆ -ARTHIES   ┆   ┆            ┆            ┆           ┆           │
│ 95  ┆ Val-d'Oise ┆ 95678      ┆ VILLIERS-A ┆ … ┆ 0.050017   ┆ 0.040791   ┆ 0.000005  ┆ 0.003177  │
│     ┆            ┆            ┆ DAM        ┆   ┆            ┆            ┆           ┆           │
│ 95  ┆ Val-d'Oise ┆ 95680      ┆ VILLIERS-L ┆ … ┆ -0.006387  ┆ -0.015119  ┆ -0.009224 ┆ 0.003177  │
│     ┆            ┆            ┆ E-BEL      ┆   ┆            ┆            ┆           ┆           │
│ 95  ┆ Val-d'Oise ┆ 95682      ┆ VILLIERS-L ┆ … ┆ -0.00251   ┆ -0.011275  ┆ -0.068388 ┆ -0.068388 │
│     ┆            ┆            ┆ E-SEC      ┆   ┆            ┆            ┆           ┆           │
│ 95  ┆ Val-d'Oise ┆ 95690      ┆ WY-DIT-JOL ┆ … ┆ 0.060216   ┆ 0.050899   ┆ -0.033168 ┆ -0.033168 │
│     ┆            ┆            ┆ I-VILLAGE  ┆   ┆            ┆            ┆           ┆           │
└─────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘